// Phasen 5–9
module.exports = {
  5: ['Phase 5 – Genehmigungen, Anzeigen und Strahlenschutz', [
    ['Baugenehmigung/Bauanzeige klären; Bauantrag mit Behörde abstimmen', 'AR,PL', 'AR', 'hoch'],
    ['Strahlenschutz-Genehmigung bzw. -Anzeige nach StrlSchG vorbereiten', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Strahlenschutzbeauftragten benennen und Zuständigkeiten festlegen', 'StrS,PL', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Sachverständigen für Strahlenschutzprüfung frühzeitig einbinden', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Umgangsgenehmigung radioaktive Stoffe beantragen', 'StrS', 'StrS', 'hoch', null, 'PET-CT'],
    ['Anzeige nach MPBetreibV/Anzeigepflichten gegenüber Behörden terminieren', 'MT,PL', 'MT', 'normal'],
    ['Arbeitsstättenrechtliche Anforderungen prüfen (ASR, Lüftung, Beleuchtung, Flucht)', 'AS,AR', 'AS', 'normal'],
    ['Gefährdungsbeurteilung Magnetfeld erstellen (Zutritt, Implantatträger, Arbeitsmittel)', 'AS,MT', 'AS', 'hoch', null, 'MRT'],
    ['Druckbehälter-/Kryogenik-Anforderungen prüfen (Helium, Sicherheitsventile)', 'AS,MT', 'AS', 'normal', null, 'MRT'],
    ['Brandschutznachweis/Abweichungen mit Prüfingenieur klären', 'BS', 'BS', 'hoch'],
    ['Denkmalschutz/Bestandsschutz-Belange klären (falls einschlägig)', 'AR', 'AR', 'niedrig'],
    ['Beteiligung Personalrat und Datenschutz für Einführung/Überwachungstechnik einleiten', 'PL', 'PL', 'normal'],
    ['Hygienefreigabe der Planung durch Krankenhaushygiene einholen', 'HYG', 'HYG', 'normal'],
    ['Aufsichtsbehörde Arbeitsschutz informieren (falls anzeigepflichtige Baustelle)', 'AS', 'AS', 'niedrig'],
    ['SiGe-Koordinator bestellen und SiGe-Plan aufstellen lassen', 'AS,AR', 'AS', 'normal'],
    ['Genehmigungsauflagen in Planung und Ausschreibung übernehmen (Auflagenliste führen)', 'PL', 'PL', 'hoch'],
    ['Entwässerungs-/Abwasseranforderungen klären (Abklinganlage, Amalgam u. ä.)', 'SAN,StrS', 'SAN', 'normal', null, 'PET-CT'],
    ['Genehmigungsstatus-Übersicht führen und im Lenkungskreis berichten', 'PL', 'PL', 'normal'],
  ]],
  6: ['Phase 6 – Ausschreibung und Vergabe', [
    ['Vergabestrategie festlegen (Verfahrensart, Lose Gerät/Bau, Wartung)', 'VG,PL', 'VG', 'hoch'],
    ['Leistungsverzeichnis Großgerät erstellen (technische Mindestanforderungen, Optionen, Applikation)', 'MT,VG', 'MT', 'hoch'],
    ['Bewertungsmatrix und Zuschlagskriterien definieren (Preis, Technik, Service, TCO)', 'VG,MT', 'VG', 'hoch'],
    ['Cybersecurity-Anforderungen in LV aufnehmen (MDS2, Patchprozess, Fernwartung, Härtung)', 'IT,MT,VG', 'IT', 'hoch'],
    ['IT-Schnittstellen ausschreiben (DICOM, HL7/RIS-PACS, Worklist, Dosismanagement)', 'IT,MT', 'IT', 'hoch'],
    ['Bau-/TGA-Leistungen ausschreiben (Lose, Terminvorgaben, Baustellenlogistik)', 'AR,VG', 'AR', 'hoch'],
    ['Wartungsvertrag ausschreiben/verhandeln (Reaktionszeiten, Verfügbarkeit, Remote-Service)', 'VG,MT', 'VG', 'hoch'],
    ['Einweisungs-/Schulungsleistungen und Applikationstage vertraglich festlegen', 'MT,VG', 'MT', 'normal'],
    ['Demontage/Rücknahme Altgerät in LV aufnehmen', 'MT,VG', 'MT', 'normal'],
    ['Lieferbedingungen definieren: Einbringung, Versicherung, Gefahrübergang, Zwischenlager', 'VG,MT,AR', 'VG', 'normal'],
    ['Bietergespräche/Teststellungen bzw. Referenzbesichtigungen durchführen', 'MT,VG', 'MT', 'normal'],
    ['Angebote technisch prüfen und Site-Planning-Anforderungen vergleichen', 'MT,AR,ELT,KÄL', 'MT', 'hoch'],
    ['Vergabevermerk erstellen; Zuschlag dokumentieren', 'VG', 'VG', 'hoch'],
    ['Verhandlungsergebnisse (Preise, Optionen, Termine) im Vertrag fixieren', 'VG,PL', 'VG', 'hoch'],
    ['Bestellung auslösen und Auftragsbestätigung mit Lieferterminen ablegen', 'VG', 'VG', 'hoch'],
    ['Finale Herstellerplanung (verbindliche Installationszeichnungen) anfordern', 'MT,AR', 'MT', 'hoch'],
    ['Bauverträge schließen; Nachunternehmerliste und Bürgschaften prüfen', 'AR,VG', 'VG', 'normal'],
    ['Terminplan mit allen Auftragnehmern verbindlich abstimmen (Bau, Lieferung, IBN)', 'PL,AR,MT', 'PL', 'hoch'],
    ['Versicherungen prüfen (Bauleistung, Transport, Montage)', 'PL,VG', 'PL', 'normal'],
    ['Förderrechtliche Vergabedokumentation sicherstellen (Prüfpfad)', 'VG,PL', 'VG', 'normal'],
  ]],
  7: ['Phase 7 – Cybersecurity und IT-Integration', [
    ['MDS2-Dokument des Herstellers anfordern und bewerten', 'IT,MT', 'IT', 'hoch'],
    ['Netzsegmentierung festlegen (Medizintechnik-VLAN, Firewall-Regeln, Zonenmodell)', 'IT', 'IT', 'hoch'],
    ['IP-Adresskonzept und Namenskonvention abstimmen', 'IT', 'IT', 'normal'],
    ['Fernwartungszugang definieren (VPN, Jump-Host, Protokollierung, Freigabeprozess)', 'IT,MT', 'IT', 'hoch'],
    ['Patch- und Updateprozess mit Hersteller vereinbaren (Verantwortung, Zyklen)', 'IT,MT', 'IT', 'hoch'],
    ['Virenschutz/Whitelisting-Konzept für Modalität klären', 'IT', 'IT', 'normal'],
    ['Schnittstellen konfigurieren: DICOM-Knoten, Worklist, MPPS, Storage-Commitment', 'IT,MT', 'IT', 'hoch'],
    ['RIS/PACS-Integration testen (Testumgebung, Testpatienten, Mapping)', 'IT,MT', 'IT', 'hoch'],
    ['Dosismanagement-Anbindung einrichten', 'IT,MT,StrS', 'IT', 'normal', null, 'CT,Angiographie,Hybrid-OP,PET-CT'],
    ['Backup-/Restore-Konzept für Gerätekonfiguration klären', 'IT,MT', 'IT', 'normal'],
    ['AD-/Benutzerkonzept am Gerät festlegen (persönliche Kennungen, Rollen)', 'IT,MT', 'IT', 'normal'],
    ['Zeitsynchronisation (NTP) und Protokollierung einrichten', 'IT', 'IT', 'niedrig'],
    ['Risikobewertung Informationssicherheit (B3S-Kontext) dokumentieren', 'IT,PL', 'IT', 'hoch'],
    ['Freigabe der IT-Sicherheitskonzeption durch ISB einholen', 'IT,PL', 'IT', 'hoch'],
    ['Notfallkonzept IT-Ausfall (Offline-Betrieb, Downtime-Formulare) erstellen', 'IT,MT', 'IT', 'normal'],
    ['Datenschutz-Folgenabschätzung prüfen/erstellen (Patientendaten am Gerät)', 'IT,PL', 'PL', 'normal'],
    ['WLAN-Ausleuchtung für mobile Workflows prüfen', 'IT', 'IT', 'niedrig'],
    ['Lizenz- und Zertifikatsverwaltung klären (DICOM-TLS, Serverzertifikate)', 'IT', 'IT', 'niedrig'],
  ]],
  8: ['Phase 8 – Bauvorbereitung', [
    ['Baustelleneinrichtung planen: Flächen, Container, Kran, Schuttwege, Anlieferzone', 'AR,PL', 'AR', 'normal'],
    ['Baustellenordnung Klinik und Zutrittsregelung kommunizieren', 'AR,AS,HYG', 'AR', 'normal'],
    ['Interims-/Umzugsplanung für betroffene Nutzer umsetzen', 'PL', 'PL', 'hoch'],
    ['Staubschutz-/Hygieneschutzkonzept mit Krankenhaushygiene festlegen (Schleusen, Unterdruck)', 'HYG,AR', 'HYG', 'hoch'],
    ['Lärm-/Erschütterungsfenster mit Klinikbetrieb vereinbaren', 'AR,PL', 'AR', 'normal'],
    ['Medienfreischaltungen planen (Strom, Wasser, Gase) und Abschaltanträge stellen', 'ELT,SAN,KÄL,LÜF', 'AR', 'hoch'],
    ['Provisorien planen (Ersatzversorgung, Umleitungen von Trassen)', 'ELT,SAN,LÜF', 'ELT', 'normal'],
    ['Bestandsleitungen orten und kennzeichnen (Leitungsauskunft, Suchschlitze)', 'AR,ELT,SAN', 'AR', 'normal'],
    ['Schadstoffsanierung beauftragen und freimessen lassen', 'AR,AS', 'AR', 'hoch'],
    ['Brandschutz während Bauphase organisieren (BMA-Abschaltungen, Heißarbeiten, Brandwachen)', 'BS,AS', 'BS', 'hoch'],
    ['Fluchtwegkonzept Bauphase mit Feuerwehr/Brandschutzbeauftragtem abstimmen', 'BS,AR', 'BS', 'normal'],
    ['Anlaufbesprechung mit allen Gewerken durchführen; Bauzeitenplan detaillieren', 'PL,AR', 'AR', 'hoch'],
    ['Bautagebuch-Führung und Fotodokumentation festlegen', 'AR,PL', 'AR', 'normal'],
    ['Beweissicherung Nachbarbereiche abschließen', 'AR', 'AR', 'normal'],
    ['Altgeräte-Demontage terminieren: Abtransport, ggf. Heliumabbau, Verwertungsnachweis', 'MT,AR', 'MT', 'normal'],
    ['Freigabe Baubeginn dokumentieren', 'PL', 'PL', 'hoch'],
  ]],
  9: ['Phase 9 – Bauphase und Rohinstallation', [
    ['Abbruch-/Demontagearbeiten überwachen; Entsorgungsnachweise sammeln', 'AR', 'AR', 'normal'],
    ['Rohbau: Durchbrüche, Fundamentplatte, Estrich, Bodenqualität prüfen', 'AR', 'AR', 'hoch'],
    ['Lastverteilplatte/Fundament nach Herstellerplan herstellen und abnehmen', 'AR,MT', 'AR', 'hoch'],
    ['Maßkontrolle Rohbau gegen Installationszeichnung (Achsen, Höhen, Toleranzen)', 'AR,MT', 'AR', 'hoch'],
    ['Bleiabschirmung einbauen; Fugen/Stöße/Durchdringungen dokumentieren', 'StrS,AR', 'StrS', 'hoch', 'Fotodokumentation vor Beplankung', 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Bleigleichwert-Zwischenprüfung vor Verschließen der Wände', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['HF-Kabine montieren (Boden, Wände, Decke, Tür, Fenster, Filterplatte)', 'MT,AR', 'MT', 'hoch', null, 'MRT'],
    ['HF-Zwischenmessung nach Kabinenmontage durchführen und protokollieren', 'MT', 'MT', 'hoch', 'Vor Innenausbau!', 'MRT'],
    ['Quenchrohr installieren; Dichtheit und Ausblasbereich sichern', 'MT,LÜF,AR', 'MT', 'hoch', null, 'MRT'],
    ['Elektro-Rohinstallation: Trassen, Leerrohre, Unterverteilung, Zählerplätze', 'ELT', 'ELT', 'normal'],
    ['Geräteeinspeisung verlegen und Querschnitte prüfen', 'ELT', 'ELT', 'hoch'],
    ['Potentialausgleich installieren; Messprotokoll Rohinstallation', 'ELT', 'ELT', 'hoch'],
    ['Kaltwasserleitungen verlegen, spülen, Druckprobe durchführen', 'KÄL,SAN', 'KÄL', 'hoch'],
    ['RLT-Kanäle montieren; Dichtheitsklasse prüfen; Brandschutzklappen einbauen', 'LÜF,BS', 'LÜF', 'normal'],
    ['Sanitär-/Gase-Rohinstallation; Druckproben medizinische Gase protokollieren', 'SAN', 'SAN', 'hoch'],
    ['MSR-Verkabelung und Feldgeräte installieren', 'MSR', 'MSR', 'normal'],
    ['IT-Verkabelung: Datendosen, LWL, Rangierung; Messprotokolle Klasse EA', 'IT', 'IT', 'normal'],
    ['Brandabschottungen herstellen und kennzeichnen (Abschottungsliste)', 'BS', 'BS', 'hoch'],
    ['Türen/Zargen einbauen (Strahlenschutz-, HF-, Fluchtwegtüren) und einstellen', 'AR,StrS', 'AR', 'normal'],
    ['Decken schließen erst nach Freigabe aller Zwischenprüfungen', 'AR,PL', 'AR', 'hoch'],
    ['Innenausbau: Böden (leitfähig), Wände, Strahlenschutz-Sichtfenster, Einbauten', 'AR', 'AR', 'normal'],
    ['Baubesprechungen wöchentlich führen; offene Punkte nachverfolgen', 'PL,AR', 'AR', 'normal'],
    ['Bautagebuch mit Fotos je Bauzustand führen', 'AR', 'AR', 'normal'],
    ['Mängel laufend erfassen und mit Fristen verfolgen', 'AR,PL', 'AR', 'normal'],
    ['Änderungsmanagement: Nachträge bewerten, freigeben, dokumentieren', 'PL,VG,AR', 'PL', 'hoch'],
    ['Raumbuch-Planstand „Ausführung" fortschreiben', 'PL,AR', 'PL', 'normal'],
  ]],
};
