// Dokumente A–F (genau 67), Raumbuch-Attribute, Raumtypen
const dokumente = {
  A: ['Bedarf, Genehmigungen und Behörden', [
    ['Bedarfsanforderung / Projektauftrag', 'PL', 'Freigegebener Projektauftrag mit Bedarfsbegründung der Klinik'],
    ['Wirtschaftlichkeitsbetrachtung', 'PL', 'Investitions- und Betriebskostenrechnung mit Amortisation'],
    ['Förderbescheid inkl. Auflagen', 'PL', 'Bewilligung der Fördermittel mit Nebenbestimmungen'],
    ['Baugenehmigung / Bauanzeige', 'AR', 'Baurechtliche Freigabe der Umbaumaßnahme'],
    ['Strahlenschutz-Genehmigung/-Anzeige', 'StrS', 'Genehmigung bzw. Anzeige nach StrlSchG für den Betrieb'],
    ['Bestellung Strahlenschutzbeauftragter', 'StrS', 'Benennungsschreiben mit Zuständigkeitsbereich'],
    ['Statik-Gutachten Aufstellort', 'AR', 'Tragfähigkeitsnachweis für Gerätelasten'],
    ['Schwingungsgutachten', 'AR', 'Messbericht Schwingungen mit Bewertung gegen Herstellergrenzwerte'],
    ['Schadstoffgutachten / Freimessung', 'AS', 'Beprobung und Freigabe nach Sanierung'],
    ['Gefährdungsbeurteilungen (Magnetfeld/Baustelle)', 'AS', 'GBU nach ArbSchG inkl. Maßnahmen'],
  ]],
  B: ['Vergabe und Vertrag', [
    ['Leistungsverzeichnis Großgerät', 'VG', 'Ausschreibungsunterlage mit technischen Anforderungen'],
    ['Vergabevermerk / Zuschlagsdokumentation', 'VG', 'Dokumentation der Angebotswertung und Vergabeentscheidung'],
    ['Kaufvertrag / Auftragsbestätigung Gerät', 'VG', 'Vertragsdokument mit Lieferumfang, Preisen und Terminen'],
    ['Wartungs-/Servicevertrag', 'VG', 'Vollwartungs- oder Servicevertrag mit Reaktionszeiten'],
    ['Finale Installationsplanung des Herstellers', 'MT', 'Verbindliche Installationszeichnungen und bauseitige Anforderungen'],
    ['Bauverträge / Nachunternehmerliste', 'AR', 'VOB-Verträge der Baugewerke'],
    ['Terminplan (Vertragsbasis)', 'PL', 'Abgestimmter Rahmenterminplan als Vertragsbestandteil'],
    ['Transport- und Montageversicherungsnachweis', 'VG', 'Versicherungsbestätigung für Lieferung und Montage'],
    ['Bürgschaften (Anzahlung/Gewährleistung)', 'VG', 'Sicherheiten gemäß Vertrag'],
    ['Demontage-/Rücknahmevereinbarung Altgerät', 'MT', 'Regelung zu Abbau, Abtransport und Verwertung'],
  ]],
  C: ['Cybersecurity und IT', [
    ['MDS2-Formular des Herstellers', 'IT', 'Manufacturer Disclosure Statement for Medical Device Security'],
    ['IT-Sicherheitskonzept / Netzsegmentierung', 'IT', 'Zonenmodell, Firewall-Regeln, Härtungsvorgaben'],
    ['Fernwartungsvereinbarung', 'IT', 'Zugriffsweg, Protokollierung und Freigabeprozess'],
    ['Patch- und Update-Vereinbarung', 'IT', 'Verantwortlichkeiten und Zyklen für Sicherheitsupdates'],
    ['Netzplan / IP-Konzept Modalität', 'IT', 'Netzwerkanbindung mit Adressen und VLANs'],
    ['Schnittstellenspezifikation DICOM/HL7', 'IT', 'Conformance Statements und Mapping-Festlegungen'],
    ['Integrationstest-Protokoll RIS/PACS', 'IT', 'Nachweis der erfolgreichen Anbindung inkl. Worklist'],
    ['Freigabe Informationssicherheit (ISB)', 'IT', 'Freigabeerklärung des Informationssicherheitsbeauftragten'],
    ['Datenschutz-Dokumentation (DSFA/VVT-Beitrag)', 'PL', 'Datenschutzrechtliche Bewertung der Verarbeitung'],
    ['IT-Notfallkonzept Modalität', 'IT', 'Downtime-Verfahren und Wiederanlaufplan'],
  ]],
  D: ['Technische Nachweise Bau und TGA', [
    ['Strahlenschutzberechnung', 'StrS', 'Berechnung der Abschirmung mit Bleigleichwerten'],
    ['Bleigleichwert-Nachweis / Einbaudokumentation', 'StrS', 'Materialnachweise und Fotodokumentation der Abschirmung'],
    ['HF-Zwischenmessung Kabine', 'MT', 'Messprotokoll Schirmdämpfung nach Kabinenmontage'],
    ['HF-Endmessung Kabine', 'MT', 'Abschlussmessung der HF-Schirmdämpfung'],
    ['Druckprobenprotokolle Kaltwasser', 'KÄL', 'Dichtheitsnachweis der Kühlkreisläufe'],
    ['Druckproben-/Reinheitsprotokolle medizinische Gase', 'SAN', 'Abnahmeprüfung nach DIN EN ISO 7396-1'],
    ['E-Messprotokolle (Iso, Schleife, RCD)', 'ELT', 'Elektrische Sicherheitsmessungen der Installation'],
    ['Abnahmeprotokoll DIN VDE 0100-710', 'ELT', 'Prüfbericht für medizinisch genutzte Bereiche'],
    ['Netzersatz-/USV-Funktionsprobe', 'ELT', 'Protokoll Lastübernahme und Autonomiezeit'],
    ['RLT-Einregulierungsprotokoll', 'LÜF', 'Volumenströme, Druckverhältnisse, Filterklassen'],
    ['Brandschutz-Abschottungsliste mit Nachweisen', 'BS', 'Verzeichnis aller Abschottungen mit Zulassungen'],
    ['Wirk-Prinzip-Prüfung BMA/Lüftung', 'BS', 'Nachweis des Zusammenwirkens der Brandschutztechnik'],
    ['IT-Verkabelungsmessprotokolle', 'IT', 'Abnahmemessung Kupfer/LWL-Strecken'],
    ['Fundament-/Lastverteilplatten-Abnahme', 'AR', 'Nachweis der Ausführung nach Herstellervorgabe'],
  ]],
  E: ['Abnahme, Prüfung und Einweisung', [
    ['Sachverständigen-Prüfbericht Strahlenschutz', 'StrS', 'Prüfung vor Inbetriebnahme mit Behördenfreigabe'],
    ['Abnahmeprüfung nach QS-Richtlinie', 'MT', 'Abnahmeprüfung mit Bezugswerten für Konstanzprüfung'],
    ['Geräteabnahmeprotokoll Hersteller', 'MT', 'Funktionsnachweis und Spezifikationsabgleich'],
    ['Sicherheitstechnische Kontrolle (STK) Erstprüfung', 'MT', 'Erstprüfung nach MPBetreibV'],
    ['DGUV-V3-Prüfprotokoll', 'ELT', 'Elektrische Prüfung der Anlagen und Betriebsmittel'],
    ['VOB-Abnahmeprotokolle je Gewerk', 'AR', 'Förmliche Bauabnahmen mit Mängellisten'],
    ['Brandschutz-Abnahmebescheinigung', 'BS', 'Freigabe durch Prüfsachverständigen'],
    ['Hygiene-Abnahmeprotokoll', 'HYG', 'Freigabe durch Krankenhaushygiene'],
    ['Magnetfeldkarte / Zonenkennzeichnung', 'MT', 'Dokumentation der 0,5-mT-Linie und Zutrittsregelung'],
    ['Ersteinweisung nach § 10 MPBetreibV', 'MT', 'Nachweis der Ersteinweisung durch Herstellerbeauftragten'],
    ['Einweisungsnachweise Anwender', 'MT', 'Unterschriebene Einweisungsliste aller Anwender'],
    ['Strahlenschutzunterweisungen', 'StrS', 'Nachweis der jährlichen Unterweisungen'],
    ['Notfall-/Quencheinweisung', 'AS', 'Unterweisung Notfallszenarien im MR-Bereich'],
  ]],
  F: ['Betrieb und Übergabe', [
    ['Medizinproduktebuch / Bestandsverzeichnis', 'MT', 'Führung nach MPBetreibV ab Inbetriebnahme'],
    ['Wartungsplan / Wartungsvertrag aktiviert', 'MT', 'Terminierte Wartungen und Zuständigkeiten'],
    ['Revisionsunterlagen / Bestandspläne', 'AR', 'As-built-Pläne aller Gewerke'],
    ['Raumbuch as built', 'PL', 'Eingefrorener Raumbuch-Endstand für den Betrieb'],
    ['Betriebsanweisungen (Magnetfeld/Strahlenschutz/Notfall)', 'AS', 'Ausgehängte Anweisungen für den Betrieb'],
    ['Übergabeprotokoll an Betrieb/CAFM', 'PL', 'Formale Übergabe mit Anlagenliste'],
    ['Gewährleistungsübersicht', 'PL', 'Fristen und Ansprechpartner je Vertrag'],
    ['Verwendungsnachweis Fördermittel', 'PL', 'Abschließender Nachweis gegenüber Fördergeber'],
    ['Entsorgungs-/Verwertungsnachweise Altgerät', 'MT', 'Nachweis inkl. Datenträgerlöschung'],
    ['Projektabschlussbericht', 'PL', 'Abschlussbericht mit Kosten- und Terminbilanz'],
  ]],
};

const attribute = [
  // AR – Architektur/Bau
  ['AR', 'Bodenbelastung', 'zahl', 'kN/m²', null, 'Zulässige Flächenlast am Aufstellort'],
  ['AR', 'Punktlast Gerät', 'zahl', 'kN', null, 'Maximale Punktlast je Aufstellfuß'],
  ['AR', 'Lichte Raumhöhe', 'zahl', 'm', null, 'Nach Ausbau, unter Decke'],
  ['AR', 'Türbreite lichte Öffnung', 'zahl', 'cm', null, 'Wichtig für Einbringung und Betten'],
  ['AR', 'Bodenbelag', 'auswahl', null, 'PVC leitfähig,Kautschuk,Fliese,Estrich', 'Leitfähigkeit im Untersuchungsraum beachten'],
  ['AR', 'Schwingungsentkopplung', 'janein', null, null, 'Erforderlich laut Herstellervorgabe?'],
  ['AR', 'Lastverteilplatte', 'janein', null, null, null],
  ['AR', 'Deckenabhängung für Stative', 'janein', null, null, 'Unterkonstruktion für Deckenstativ/Ampel'],
  // ELT
  ['ELT', 'Anschlussleistung Gerät', 'zahl', 'kVA', null, 'Lt. Herstellerdatenblatt'],
  ['ELT', 'Einspeisung Querschnitt', 'text', null, null, 'z. B. 4×95 mm² Cu'],
  ['ELT', 'Steckdosen AV', 'zahl', 'Stk', null, 'Allgemeine Versorgung'],
  ['ELT', 'Steckdosen SV', 'zahl', 'Stk', null, 'Sicherheitsversorgung (NEA)'],
  ['ELT', 'Steckdosen ZSV', 'zahl', 'Stk', null, 'Zusätzliche Sicherheitsversorgung (IT-System)'],
  ['ELT', 'Raumgruppe VDE 0100-710', 'auswahl', null, '0,1,2', null],
  ['ELT', 'Potentialausgleich', 'janein', null, null, 'Zentraler PA-Punkt vorhanden'],
  ['ELT', 'USV-Versorgung', 'janein', null, null, 'Für Rechner/Konsole'],
  ['ELT', 'Beleuchtungsstärke', 'zahl', 'lx', null, 'Nach ASR/DIN EN 12464'],
  ['ELT', 'Dimmbare Beleuchtung', 'janein', null, null, 'Für Untersuchungsbetrieb'],
  ['ELT', 'Not-Aus Gerät', 'janein', null, null, 'Position mit Nutzer abstimmen'],
  // IT
  ['IT', 'Datendosen', 'zahl', 'Stk', null, 'Doppeldosen RJ45'],
  ['IT', 'LWL-Anbindung', 'janein', null, null, 'Direktanbindung an Verteiler'],
  ['IT', 'Netzwerksegment/VLAN', 'text', null, null, 'z. B. VLAN Medizintechnik 210'],
  ['IT', 'WLAN-Ausleuchtung', 'janein', null, null, null],
  ['IT', 'Patchweg dokumentiert', 'text', null, null, 'Verteiler/Port'],
  // MT
  ['MT', 'Geräteliste Raum', 'text', null, null, 'Hauptgerät und Zusatzgeräte'],
  ['MT', 'Deckenstativ', 'janein', null, null, null],
  ['MT', 'Injektor-Standort', 'text', null, null, null],
  ['MT', 'HF-Schirmdämpfung Soll', 'zahl', 'dB', null, 'Lt. Hersteller, typ. ≥ 90 dB'],
  ['MT', 'Magnetfeld 0,5-mT-Linie', 'text', null, null, 'Verlauf/Kennzeichnung'],
  ['MT', 'Patientenüberwachung', 'text', null, null, 'Monitoring, Kamera, Sprechanlage'],
  ['MT', 'Medizinische Gase am Platz', 'janein', null, null, null],
  // LÜF
  ['LÜF', 'Luftwechselrate', 'zahl', '1/h', null, 'Lt. Hygiene-/Herstellervorgabe'],
  ['LÜF', 'Raumtemperatur Sollbereich', 'text', '°C', null, 'z. B. 20–24 °C, ±1 K/h Gradient'],
  ['LÜF', 'Relative Feuchte Sollbereich', 'text', '%', null, 'z. B. 40–60 %'],
  ['LÜF', 'Druckstufe', 'auswahl', null, 'Überdruck,Neutral,Unterdruck', null],
  ['LÜF', 'Filterklasse Zuluft', 'text', null, null, 'z. B. ePM1 55% + HEPA je Anforderung'],
  ['LÜF', 'Quench-Abluftführung', 'janein', null, null, 'Nur MRT: Verhalten bei Quench geklärt'],
  // KÄL
  ['KÄL', 'Kühllast Gerät', 'zahl', 'kW', null, 'Wärmeabgabe an Kaltwasser'],
  ['KÄL', 'Kühllast Raum (Luft)', 'zahl', 'kW', null, 'Wärmeabgabe an Raumluft'],
  ['KÄL', 'Kaltwasseranschluss', 'janein', null, null, null],
  ['KÄL', 'Vorlauftemperatur', 'zahl', '°C', null, 'Lt. Hersteller, typ. 6–12 °C'],
  ['KÄL', 'Redundanz/Notkühlung', 'janein', null, null, 'Bei Ausfall Hauptkälte'],
  // SAN
  ['SAN', 'Waschplatz', 'janein', null, null, null],
  ['SAN', 'Ausgussbecken', 'janein', null, null, null],
  ['SAN', 'Bodenablauf', 'janein', null, null, 'Rückstauebene beachten'],
  ['SAN', 'Medizinische Gase', 'auswahl', null, 'O2,Druckluft,Vakuum,O2+Druckluft,O2+Druckluft+Vakuum,keine', null],
  ['SAN', 'Gase-Entnahmestellen', 'zahl', 'Stk', null, null],
  // StrS
  ['StrS', 'Bleigleichwert Wände', 'zahl', 'mm Pb', null, 'Aus Strahlenschutzberechnung'],
  ['StrS', 'Bleigleichwert Tür', 'zahl', 'mm Pb', null, null],
  ['StrS', 'Bleigleichwert Fenster', 'zahl', 'mm Pb', null, 'Bleiglas Sichtfenster'],
  ['StrS', 'Bleigleichwert Decke/Boden', 'zahl', 'mm Pb', null, null],
  ['StrS', 'Kontrollbereich', 'janein', null, null, 'Kennzeichnung erforderlich'],
  ['StrS', 'Warnleuchte/Türkontakt', 'janein', null, null, null],
  // MSR
  ['MSR', 'GLT-Aufschaltung', 'janein', null, null, null],
  ['MSR', 'Datenpunkte Anzahl', 'zahl', 'Stk', null, null],
  ['MSR', 'Störmeldung an Leitwarte', 'janein', null, null, 'Kritische Meldungen definiert'],
  ['MSR', 'O2-Überwachung', 'janein', null, null, 'Nur MRT-Technik/Untersuchungsraum'],
  ['MSR', 'Temperaturüberwachung Technikraum', 'janein', null, null, null],
  // HZG
  ['HZG', 'Heizlast', 'zahl', 'kW', null, null],
  ['HZG', 'Heizsystem', 'auswahl', null, 'Statisch,Lüftung,Keins', null],
  // BS
  ['BS', 'Brandabschnitt', 'text', null, null, 'Zuordnung/Bezeichnung'],
  ['BS', 'Brandmelder Anzahl', 'zahl', 'Stk', null, null],
  ['BS', 'Feuerwiderstand Türen', 'text', null, null, 'z. B. T30-RS'],
  ['BS', 'Löschmittel MR-tauglich', 'janein', null, null, 'Amagnetischer Feuerlöscher im MR-Bereich'],
  // HYG
  ['HYG', 'Raumklasse Hygiene', 'auswahl', null, 'I,Ia,Ib,II,ohne', 'Einstufung durch Krankenhaushygiene'],
  ['HYG', 'Händedesinfektionsspender', 'zahl', 'Stk', null, null],
  ['HYG', 'Oberflächen desinfektionsbeständig', 'janein', null, null, null],
  // AS
  ['AS', 'Fluchtweg', 'text', null, null, 'Führung/Länge'],
  ['AS', 'Notruf/Patientenruf', 'janein', null, null, null],
  ['AS', 'Augenspüleinrichtung', 'janein', null, null, 'Bei KM-/Chemikalienhandling'],

  // ---- Raumbuch 2.0 (AP-16): ergänzte Merkmale für die geführte Vollabfrage ----
  // AR
  ['AR', 'Einbringöffnung B×H', 'text', 'm', null, 'Größte Komponente (Magnet/Gantry) inkl. Transportmaß prüfen'],
  ['AR', 'Einbringweg geprüft', 'janein', null, null, 'Route inkl. Zwischentüren, Aufzügen und Bodenlasten entlang des Wegs'],
  ['AR', 'Fußbodenaufbau', 'text', null, null, 'Aufbauhöhe, Kanal-/Trassenführung, ggf. Doppelboden'],
  ['AR', 'Schallschutz Anforderung', 'text', 'dB', null, 'Gradientenlärm MRT: Anforderung an Wände, Türen, Decke'],
  ['AR', 'Fenster/Tageslicht', 'janein', null, null, 'ASR A3.4 beachten, ggf. Kompensationsmaßnahmen'],
  ['AR', 'Sichtfenster zum Bedienraum', 'janein', null, null, 'Direkte Sicht auf den Patienten'],
  // ELT
  ['ELT', 'Netzform', 'auswahl', null, 'TN-S,IT-System (Gruppe 2),Sonstige', 'Nach Raumgruppe VDE 0100-710'],
  ['ELT', 'Filterdurchführungen HF-Kabine', 'zahl', 'Stk', null, 'Alle Leitungen in den Magnetraum nur über die Filterplatte'],
  ['ELT', 'Beleuchtung MR-tauglich', 'janein', null, null, 'Im Magnetraum DC-gespeist bzw. herstellerfreigegeben'],
  ['ELT', 'Magnet-Stop (ERDU) Position', 'text', null, null, 'Not-Abschaltung des Magneten: Position mit Nutzer und Hersteller abstimmen'],
  ['ELT', 'Kabelweg Gerät–Technikraum', 'zahl', 'm', null, 'Maximale Kabellängen laut Hersteller einhalten'],
  // MT
  ['MT', 'Quenchrohr', 'text', null, null, 'Querschnitt, Führung, Ausblasort im Freien (Personenschutz!), Schnee-/Vogelschutz'],
  ['MT', '5-Gauss-Linie Zutrittskonzept', 'text', null, null, 'Kennzeichnung und Zutrittsregelung, auch angrenzende Räume und Geschosse'],
  ['MT', 'Magnetische Störquellen Umfeld', 'text', null, null, 'Aufzüge, Fahrwege, Stahlbau, bewegte Massen – Grenzwerte laut Hersteller'],
  ['MT', 'HF-Kabine Abnahmemessung', 'janein', null, null, 'Messprotokoll der Schirmdämpfung vor Gerätelieferung'],
  ['MT', 'Heliumbefüllung Zugang', 'text', null, null, 'Weg für Heliumgebinde und Servicegeräte bis zum Magneten'],
  ['MT', 'Spulen-/Zubehörlagerung', 'text', null, null, 'Schrank/Stauraum im oder nahe dem Untersuchungsraum'],
  ['MT', 'Anästhesie-Arbeitsplatz MR-tauglich', 'janein', null, null, 'Falls Sedierung/Anästhesie vorgesehen'],
  // IT
  ['IT', 'PACS/RIS-Anbindung', 'janein', null, null, 'DICOM-Knoten, Worklist, Netzfreigaben geklärt'],
  ['IT', 'Telefon/Sprechstelle', 'zahl', 'Stk', null, null],
  // KÄL
  ['KÄL', 'Rücklauftemperatur', 'zahl', '°C', null, null],
  ['KÄL', 'Volumenstrom Kaltwasser', 'zahl', 'm³/h', null, null],
  ['KÄL', 'Glykolanteil', 'zahl', '%', null, 'Wasserqualität und Frostschutz laut Hersteller'],
  ['KÄL', 'Kaltwasser bei Netzausfall', 'janein', null, null, 'MRT: Versorgung Heliumkompressor über SV prüfen (Magnetschutz)'],
  // StrS
  ['StrS', 'Strahlenschutzberechnung liegt vor', 'janein', null, null, 'Durch Strahlenschutzbeauftragten/Sachverständigen'],
  ['StrS', 'Verfahren StrlSchG', 'auswahl', null, 'Genehmigung,Anzeige,offen', 'Betriebsbeginn erst nach Genehmigung bzw. Anzeige'],
  // MSR
  ['MSR', 'O2-Alarmierungsweg', 'text', null, null, 'Meldeziel und Quittierung des Sauerstoffwächters festlegen'],
  // BS
  ['BS', 'Feuerwehr-Einsatzplan Magnetfeld-Hinweis', 'janein', null, null, 'Gefahr durch das Magnetfeld im Einsatzplan vermerkt'],
  // AS
  ['AS', 'Lärmschutz Personal', 'text', 'dB(A)', null, 'Gradientenlärm: Bewertung und Gehörschutzkonzept'],
];

// Raumbuch 2.0 (AP-16): Referenzen als Kurzform 'GEWERK:Name' oder Langform
// ['GEWERK:Name', { pflicht: 1, soll: 'Vorschlagswert', geraete: 'MRT,PET-CT' }].
// pflicht → Pflichtpunkt für Vollständigkeit; soll → Soll-Vorschlag (nicht automatisch Soll);
// geraete → Punkt wird nur bei passendem Projekt-Gerätetyp vorbelegt (leer = immer).
const raumtypen = [
  ['MRT-Untersuchungsraum', [
    // Architektur/Bau
    ['AR:Bodenbelastung', { pflicht: 1 }], ['AR:Punktlast Gerät', { pflicht: 1 }],
    ['AR:Lichte Raumhöhe', { pflicht: 1 }], 'AR:Türbreite lichte Öffnung',
    ['AR:Einbringöffnung B×H', { pflicht: 1 }], ['AR:Einbringweg geprüft', { pflicht: 1 }],
    'AR:Fußbodenaufbau', 'AR:Bodenbelag', ['AR:Schwingungsentkopplung', { pflicht: 1 }],
    'AR:Lastverteilplatte', 'AR:Schallschutz Anforderung', 'AR:Fenster/Tageslicht',
    'AR:Sichtfenster zum Bedienraum',
    // Elektro
    ['ELT:Anschlussleistung Gerät', { pflicht: 1 }], 'ELT:Netzform', 'ELT:Einspeisung Querschnitt',
    ['ELT:Raumgruppe VDE 0100-710', { pflicht: 1 }], 'ELT:Steckdosen AV', 'ELT:Steckdosen SV',
    'ELT:Steckdosen ZSV', ['ELT:Potentialausgleich', { pflicht: 1 }],
    ['ELT:Filterdurchführungen HF-Kabine', { pflicht: 1 }], ['ELT:Beleuchtung MR-tauglich', { pflicht: 1 }],
    'ELT:Dimmbare Beleuchtung', 'ELT:Not-Aus Gerät', ['ELT:Magnet-Stop (ERDU) Position', { pflicht: 1 }],
    'ELT:Kabelweg Gerät–Technikraum', 'ELT:USV-Versorgung',
    // Medizintechnik / MR-Spezifika
    ['MT:HF-Schirmdämpfung Soll', { pflicht: 1, soll: '≥ 90 dB (lt. Hersteller)' }],
    ['MT:HF-Kabine Abnahmemessung', { pflicht: 1 }], ['MT:Magnetfeld 0,5-mT-Linie', { pflicht: 1 }],
    ['MT:5-Gauss-Linie Zutrittskonzept', { pflicht: 1 }], 'MT:Magnetische Störquellen Umfeld',
    ['MT:Quenchrohr', { pflicht: 1 }], 'MT:Heliumbefüllung Zugang', 'MT:Patientenüberwachung',
    'MT:Medizinische Gase am Platz', 'MT:Spulen-/Zubehörlagerung', 'MT:Anästhesie-Arbeitsplatz MR-tauglich',
    // Lüftung/Klima
    'LÜF:Luftwechselrate', ['LÜF:Raumtemperatur Sollbereich', { soll: '20–24 °C' }],
    ['LÜF:Relative Feuchte Sollbereich', { soll: '40–60 %' }], 'LÜF:Druckstufe',
    ['LÜF:Quench-Abluftführung', { pflicht: 1 }],
    // Kälte / Sanitär / MSR
    'KÄL:Kühllast Raum (Luft)', 'SAN:Medizinische Gase', 'SAN:Gase-Entnahmestellen', 'SAN:Bodenablauf',
    ['MSR:O2-Überwachung', { pflicht: 1 }], 'MSR:O2-Alarmierungsweg', 'MSR:GLT-Aufschaltung',
    // Brandschutz / Hygiene / Arbeitssicherheit / IT
    'BS:Brandabschnitt', 'BS:Brandmelder Anzahl', ['BS:Löschmittel MR-tauglich', { pflicht: 1 }],
    ['BS:Feuerwehr-Einsatzplan Magnetfeld-Hinweis', { pflicht: 1 }],
    'HYG:Raumklasse Hygiene', 'HYG:Händedesinfektionsspender', 'HYG:Oberflächen desinfektionsbeständig',
    'AS:Fluchtweg', 'AS:Notruf/Patientenruf', 'AS:Lärmschutz Personal', 'AS:Augenspüleinrichtung',
    'IT:Datendosen', 'IT:LWL-Anbindung', 'IT:Netzwerksegment/VLAN', 'IT:PACS/RIS-Anbindung',
    'IT:Telefon/Sprechstelle', 'IT:WLAN-Ausleuchtung',
  ]],
  ['CT-Untersuchungsraum', [
    ['AR:Bodenbelastung', { pflicht: 1 }], 'AR:Punktlast Gerät', ['AR:Türbreite lichte Öffnung', { pflicht: 1 }],
    ['AR:Einbringöffnung B×H', { pflicht: 1 }], 'AR:Einbringweg geprüft', 'AR:Fußbodenaufbau',
    'AR:Bodenbelag', 'AR:Sichtfenster zum Bedienraum',
    ['ELT:Anschlussleistung Gerät', { pflicht: 1 }], 'ELT:Netzform', 'ELT:Einspeisung Querschnitt',
    ['ELT:Raumgruppe VDE 0100-710', { pflicht: 1 }], 'ELT:Steckdosen AV', 'ELT:Steckdosen SV',
    'ELT:Steckdosen ZSV', 'ELT:Potentialausgleich', 'ELT:Not-Aus Gerät', 'ELT:Kabelweg Gerät–Technikraum',
    'ELT:Beleuchtungsstärke', 'ELT:Dimmbare Beleuchtung',
    ['StrS:Strahlenschutzberechnung liegt vor', { pflicht: 1 }], ['StrS:Verfahren StrlSchG', { pflicht: 1 }],
    ['StrS:Bleigleichwert Wände', { pflicht: 1 }], ['StrS:Bleigleichwert Tür', { pflicht: 1 }],
    ['StrS:Bleigleichwert Fenster', { pflicht: 1 }], ['StrS:Bleigleichwert Decke/Boden', { pflicht: 1 }],
    ['StrS:Kontrollbereich', { pflicht: 1 }], ['StrS:Warnleuchte/Türkontakt', { pflicht: 1 }],
    'MT:Geräteliste Raum', 'MT:Patientenüberwachung', 'MT:Injektor-Standort',
    'LÜF:Luftwechselrate', ['LÜF:Raumtemperatur Sollbereich', { soll: '20–26 °C' }],
    'LÜF:Relative Feuchte Sollbereich', ['KÄL:Kühllast Raum (Luft)', { pflicht: 1 }],
    'SAN:Medizinische Gase', 'SAN:Gase-Entnahmestellen', 'SAN:Waschplatz',
    'MSR:GLT-Aufschaltung', 'BS:Brandabschnitt', 'BS:Brandmelder Anzahl',
    'HYG:Raumklasse Hygiene', 'HYG:Händedesinfektionsspender', 'HYG:Oberflächen desinfektionsbeständig',
    'AS:Fluchtweg', 'AS:Notruf/Patientenruf', 'AS:Augenspüleinrichtung',
    'IT:Datendosen', 'IT:Netzwerksegment/VLAN', 'IT:PACS/RIS-Anbindung', 'IT:Telefon/Sprechstelle',
  ]],
  ['Angiographie-/Hybrid-OP-Raum', [
    ['AR:Deckenabhängung für Stative', { pflicht: 1 }], ['AR:Lichte Raumhöhe', { pflicht: 1 }],
    ['AR:Bodenbelastung', { pflicht: 1 }], ['AR:Türbreite lichte Öffnung', { pflicht: 1 }],
    ['AR:Einbringöffnung B×H', { pflicht: 1 }], 'AR:Einbringweg geprüft', 'AR:Fußbodenaufbau', 'AR:Bodenbelag',
    ['ELT:Anschlussleistung Gerät', { pflicht: 1 }],
    ['ELT:Netzform', { pflicht: 1, soll: 'IT-System (Gruppe 2)' }],
    ['ELT:Raumgruppe VDE 0100-710', { pflicht: 1, soll: '2' }],
    'ELT:Steckdosen SV', ['ELT:Steckdosen ZSV', { pflicht: 1 }], ['ELT:Potentialausgleich', { pflicht: 1 }],
    ['ELT:USV-Versorgung', { pflicht: 1 }], 'ELT:Not-Aus Gerät', 'ELT:Kabelweg Gerät–Technikraum',
    'ELT:Beleuchtungsstärke', 'ELT:Dimmbare Beleuchtung',
    ['StrS:Strahlenschutzberechnung liegt vor', { pflicht: 1 }], ['StrS:Verfahren StrlSchG', { pflicht: 1 }],
    ['StrS:Bleigleichwert Wände', { pflicht: 1 }], ['StrS:Bleigleichwert Tür', { pflicht: 1 }],
    ['StrS:Kontrollbereich', { pflicht: 1 }], ['StrS:Warnleuchte/Türkontakt', { pflicht: 1 }],
    ['MT:Deckenstativ', { pflicht: 1 }], 'MT:Injektor-Standort', 'MT:Geräteliste Raum',
    ['MT:Medizinische Gase am Platz', { pflicht: 1 }], 'MT:Patientenüberwachung',
    ['MT:Anästhesie-Arbeitsplatz MR-tauglich', { geraete: 'Hybrid-OP' }],
    ['LÜF:Luftwechselrate', { pflicht: 1 }], ['LÜF:Druckstufe', { pflicht: 1, soll: 'Überdruck' }],
    ['LÜF:Filterklasse Zuluft', { pflicht: 1, geraete: 'Hybrid-OP' }],
    'LÜF:Raumtemperatur Sollbereich', 'LÜF:Relative Feuchte Sollbereich',
    'KÄL:Kühllast Raum (Luft)',
    ['SAN:Medizinische Gase', { pflicht: 1 }], ['SAN:Gase-Entnahmestellen', { pflicht: 1 }],
    'MSR:GLT-Aufschaltung', 'BS:Brandabschnitt', 'BS:Brandmelder Anzahl',
    ['HYG:Raumklasse Hygiene', { pflicht: 1, soll: 'Ia (Hybrid-OP)', geraete: 'Hybrid-OP' }],
    ['HYG:Raumklasse Hygiene', { pflicht: 1, geraete: 'Angiographie' }],
    'HYG:Händedesinfektionsspender', 'HYG:Oberflächen desinfektionsbeständig',
    'AS:Fluchtweg', 'AS:Notruf/Patientenruf',
    'IT:Datendosen', 'IT:LWL-Anbindung', 'IT:Netzwerksegment/VLAN', 'IT:PACS/RIS-Anbindung', 'IT:Telefon/Sprechstelle',
  ]],
  ['Technikraum', [
    'AR:Bodenbelastung', 'AR:Türbreite lichte Öffnung', 'AR:Fußbodenaufbau',
    ['ELT:Anschlussleistung Gerät', { pflicht: 1 }], 'ELT:Netzform', 'ELT:Einspeisung Querschnitt',
    'ELT:Steckdosen AV', 'ELT:USV-Versorgung',
    ['KÄL:Kühllast Gerät', { pflicht: 1 }], ['KÄL:Kaltwasseranschluss', { pflicht: 1 }],
    ['KÄL:Vorlauftemperatur', { pflicht: 1 }], 'KÄL:Rücklauftemperatur', 'KÄL:Volumenstrom Kaltwasser',
    'KÄL:Glykolanteil', ['KÄL:Redundanz/Notkühlung', { pflicht: 1 }],
    ['KÄL:Kaltwasser bei Netzausfall', { geraete: 'MRT,PET-CT' }],
    ['LÜF:Raumtemperatur Sollbereich', { soll: 'lt. Hersteller (typ. 15–24 °C)' }], 'LÜF:Luftwechselrate',
    ['MSR:GLT-Aufschaltung', { pflicht: 1 }], ['MSR:Temperaturüberwachung Technikraum', { pflicht: 1 }],
    ['MSR:Störmeldung an Leitwarte', { pflicht: 1 }],
    ['MSR:O2-Überwachung', { pflicht: 1, geraete: 'MRT,PET-CT' }],
    ['MSR:O2-Alarmierungsweg', { geraete: 'MRT,PET-CT' }],
    'BS:Brandabschnitt', 'BS:Brandmelder Anzahl',
    'IT:Datendosen', ['IT:LWL-Anbindung', { pflicht: 1 }], 'IT:Netzwerksegment/VLAN',
  ]],
  ['Bedienraum/Schaltraum', [
    'AR:Sichtfenster zum Bedienraum', 'ELT:Steckdosen AV', 'ELT:Steckdosen SV', 'ELT:USV-Versorgung',
    'ELT:Beleuchtungsstärke', 'ELT:Dimmbare Beleuchtung',
    ['StrS:Bleigleichwert Wände', { geraete: 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger' }],
    ['StrS:Bleigleichwert Fenster', { geraete: 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger' }],
    'MT:Patientenüberwachung', 'LÜF:Raumtemperatur Sollbereich',
    ['IT:Datendosen', { pflicht: 1 }], 'IT:Netzwerksegment/VLAN', 'IT:PACS/RIS-Anbindung', 'IT:Telefon/Sprechstelle',
    'HYG:Händedesinfektionsspender', 'AS:Notruf/Patientenruf', 'BS:Brandmelder Anzahl',
  ]],
  ['Vorbereitung/Patientenhaltung', [
    'SAN:Waschplatz', 'SAN:Medizinische Gase', 'SAN:Gase-Entnahmestellen',
    'ELT:Steckdosen SV', 'ELT:Raumgruppe VDE 0100-710', 'MT:Patientenüberwachung',
    'LÜF:Luftwechselrate', 'HYG:Raumklasse Hygiene', 'HYG:Händedesinfektionsspender',
    'AS:Notruf/Patientenruf', 'IT:Datendosen', 'IT:Telefon/Sprechstelle', 'BS:Brandmelder Anzahl',
  ]],
  ['Umkleide Patienten', [
    'AR:Türbreite lichte Öffnung', 'ELT:Steckdosen AV', 'LÜF:Luftwechselrate',
    'AS:Notruf/Patientenruf', 'HYG:Händedesinfektionsspender', 'BS:Brandmelder Anzahl',
  ]],
  ['Wartebereich', [
    'ELT:Steckdosen AV', 'ELT:Beleuchtungsstärke', 'LÜF:Luftwechselrate', 'LÜF:Raumtemperatur Sollbereich',
    'BS:Brandabschnitt', 'BS:Brandmelder Anzahl', 'IT:WLAN-Ausleuchtung', 'AS:Fluchtweg',
    'HYG:Händedesinfektionsspender',
  ]],
  ['Befundraum', [
    ['IT:Datendosen', { pflicht: 1 }], 'IT:Netzwerksegment/VLAN', ['IT:PACS/RIS-Anbindung', { pflicht: 1 }],
    'IT:Telefon/Sprechstelle', 'ELT:Steckdosen SV', 'ELT:USV-Versorgung', 'ELT:Beleuchtungsstärke',
    'LÜF:Raumtemperatur Sollbereich', 'BS:Brandmelder Anzahl',
  ]],
];

module.exports = { dokumente, attribute, raumtypen };
