// Phasen 0–4: [text, gewerke, fuehrend, prio, hinweis, geraetetypen]
module.exports = {
  0: ['Phase 0 – Bedarfsermittlung und Strategie', [
    ['Medizinischen Bedarf mit Klinik/Nutzern strukturiert erheben (Fallzahlen, Untersuchungsspektrum, Engpässe)', 'PL,MT', 'PL', 'hoch'],
    ['Abgleich mit Medizinstrategie und Zielplanung des Klinikums dokumentieren', 'PL', 'PL', 'hoch'],
    ['Bestandsgerät bewerten: Alter, Ausfallhistorie, Wartungskosten, Ersatzteilverfügbarkeit', 'MT', 'MT', 'hoch'],
    ['Ersatz- oder Neubeschaffung abgrenzen; Optionen Upgrade/Umzug prüfen', 'PL,MT', 'PL', 'normal'],
    ['Nutzungsdauer und Auslastungsprognose über 10 Jahre erstellen', 'PL,MT', 'PL', 'normal'],
    ['Marktübersicht Gerätetypen/Hersteller erstellen (Feldstärke, Detektortechnik, Optionen)', 'MT', 'MT', 'normal'],
    ['Anforderungen aus Forschung und Lehre abfragen (Universitätsklinikum)', 'PL,MT', 'PL', 'normal'],
    ['Erste Grobkostenschätzung Gerät + Bau + Nebenkosten aufstellen', 'PL,MT,AR', 'PL', 'hoch'],
    ['Fördermöglichkeiten prüfen (Landesförderung, EFRE, Sonderprogramme) und Fristen notieren', 'PL,VG', 'PL', 'hoch'],
    ['Projektorganisation festlegen: Rollen, Gremien, Entscheidungswege, Eskalationspfad', 'PL', 'PL', 'hoch'],
    ['Grober Terminrahmen mit Meilensteinen (Vergabe, Bau, Lieferung, Go-Live) abstimmen', 'PL', 'PL', 'normal'],
    ['Interimskonzept bei Ersatzbeschaffung klären (Ausweichgerät, Kooperation, mobile Lösung)', 'PL,MT', 'PL', 'normal'],
    ['Stilllegungs-/Weiterverwendungskonzept Altgerät skizzieren', 'MT', 'MT', 'niedrig'],
    ['Projektauftrag/Projektfreigabe durch Klinikleitung einholen und ablegen', 'PL', 'PL', 'hoch'],
  ]],
  1: ['Phase 1 – Wirtschaftlichkeit, Finanzierung und Förderung', [
    ['Wirtschaftlichkeitsbetrachtung erstellen (Investition, Betriebskosten, Erlöse, Amortisation)', 'PL', 'PL', 'hoch'],
    ['Budgetrahmen mit Kaufmännischer Direktion abstimmen und schriftlich fixieren', 'PL', 'PL', 'hoch'],
    ['Kostenschätzung Bau nach DIN 276 durch Fachplaner aufstellen lassen', 'AR', 'AR', 'hoch'],
    ['Baunebenkosten, Planungshonorare (HOAI) und Reserven (mind. 10 %) einplanen', 'PL,AR', 'PL', 'normal'],
    ['Förderantrag vorbereiten: Bedarfsbegründung, Kostenaufstellung, Terminplan', 'PL,VG', 'PL', 'hoch'],
    ['Fördervoraussetzungen und Auflagen dokumentieren (Zweckbindung, Nachweisfristen)', 'PL,VG', 'PL', 'normal'],
    ['Finanzierungsart Kauf/Leasing/Miete/Ratenkauf bewerten', 'PL,VG', 'VG', 'normal'],
    ['Wartungs- und Servicekosten (Vollwartung vs. Teilwartung) über Laufzeit kalkulieren', 'MT,VG', 'MT', 'hoch'],
    ['Energie- und Medienkosten (Strom, Kälte, Wasser) überschlägig ermitteln', 'ELT,KÄL,SAN', 'ELT', 'normal'],
    ['Personalbedarf und Qualifikation für Betrieb prüfen (MTRA, Physik, Wartung)', 'PL', 'PL', 'normal'],
    ['Freigabe der Finanzierung durch Vorstand/Aufsichtsgremium einholen', 'PL', 'PL', 'hoch'],
    ['Mittelabfluss-/Zahlungsplan mit Meilensteinen aufstellen', 'PL,VG', 'PL', 'normal'],
  ]],
  2: ['Phase 2 – Nutzungs- und Betriebskonzept', [
    ['Betriebskonzept erstellen: Betriebszeiten, Patientenpfade, Notfallverfügbarkeit', 'PL,MT', 'PL', 'hoch'],
    ['Workflow-Analyse: Anmeldung, Vorbereitung, Untersuchung, Befundung, Übergaben', 'PL,MT,HYG', 'PL', 'normal'],
    ['Raumprogramm nach DIN 13080 ableiten (Untersuchung, Technik, Bedienung, Vorbereitung, Warten)', 'AR,MT', 'AR', 'hoch'],
    ['Flächenbedarf je Raum mit Herstellervorgaben abgleichen', 'AR,MT', 'AR', 'hoch'],
    ['Personalflüsse und Patiententransporte (Betten, Liegend, Notfall) planen', 'PL,AR,HYG', 'PL', 'normal'],
    ['Anbindung an Notaufnahme, OP, Intensivstation bewerten', 'PL,AR', 'PL', 'normal'],
    ['Anforderungen Patientensicherheit/Überwachung definieren (Monitoring, Notruf, Reanimation)', 'MT,ELT,AS', 'MT', 'hoch'],
    ['Anforderungen Barrierefreiheit und Patientenkomfort festlegen', 'AR', 'AR', 'normal'],
    ['Hygienekonzept-Eckpunkte mit Krankenhaushygiene abstimmen (Raumklassen, Aufbereitung)', 'HYG', 'HYG', 'hoch'],
    ['Anforderungen Anästhesie-Arbeitsplatz klären (Gase, Absaugung, Monitoring)', 'MT,SAN', 'MT', 'normal', null, 'MRT,CT,Angiographie,Hybrid-OP,PET-CT'],
    ['Kontrastmittel-Lagerung und -Vorbereitung planen', 'MT,HYG,SAN', 'MT', 'normal'],
    ['Radiopharmaka-Handling und Abklinganforderungen klären', 'MT,StrS,HYG', 'StrS', 'hoch', null, 'PET-CT'],
    ['Betreiberverantwortung nach MPBetreibV organisatorisch zuordnen', 'MT,PL', 'MT', 'hoch'],
    ['Schulungs- und Einweisungskonzept für Anwender skizzieren', 'MT', 'MT', 'normal'],
  ]],
  3: ['Phase 3 – Standortprüfung und Bestandsaufnahme', [
    ['Standortalternativen bewerten (Flächen, Anbindung, Bauaufwand, Betrieb während Bau)', 'PL,AR', 'AR', 'hoch'],
    ['Bestandspläne beschaffen und auf Aktualität prüfen (Architektur, TGA, Statik)', 'AR', 'AR', 'hoch'],
    ['Statik/Tragfähigkeit der Decke für Gerätegewicht prüfen lassen (Gutachten)', 'AR', 'AR', 'hoch', 'MRT-Magnete 4–10 t, CT-Gantry 2–3 t'],
    ['Schwingungsuntersuchung am Aufstellort durchführen (Herstellergrenzwerte)', 'AR,MT', 'AR', 'hoch', null, 'MRT,CT,PET-CT,Angiographie'],
    ['Transportweg und Einbringöffnung prüfen: Maße, Lasten, Kranstellplatz, Zwischenlager', 'AR,MT,PL', 'AR', 'hoch'],
    ['Magnetfeld-Umgebungsanalyse: benachbarte Nutzung, Aufzüge, Stahlbau, bewegte Massen', 'MT,AR', 'MT', 'hoch', null, 'MRT'],
    ['HF-Störumgebung messen (Sender, Bahn, Funkdienste)', 'MT,ELT', 'MT', 'normal', null, 'MRT'],
    ['Bestand Elektroversorgung prüfen: Trafoleistung, NSHV-Reserven, Netzform, Kurzschlussleistung', 'ELT', 'ELT', 'hoch'],
    ['Bestand Netzersatz/USV prüfen (AV/SV/ZSV-Kapazitäten)', 'ELT', 'ELT', 'hoch'],
    ['Bestand Kälteversorgung prüfen: Kaltwassernetz, Reserven, Redundanz', 'KÄL', 'KÄL', 'hoch'],
    ['Bestand RLT prüfen: Anlagenkapazität, Kanalführung, Außenluftqualität', 'LÜF', 'LÜF', 'normal'],
    ['Bestand Sanitär/Medizingase prüfen (Leitungen, Druck, Entnahmestellen)', 'SAN', 'SAN', 'normal'],
    ['Bestand IT-Infrastruktur prüfen: Netzwerkverteiler, LWL-Strecken, Redundanz', 'IT', 'IT', 'normal'],
    ['Schadstoffkataster prüfen (Asbest, KMF, PCB) und Beprobung veranlassen', 'AR,AS', 'AR', 'hoch'],
    ['Brandschutzbestand erfassen: Abschnitte, Fluchtwege, Anlagentechnik', 'BS,AR', 'BS', 'hoch'],
    ['Strahlenschutz-Bestandssituation dokumentieren (vorhandene Abschirmungen, Genehmigungen)', 'StrS', 'StrS', 'normal', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Bauzustand angrenzender Bereiche dokumentieren (Fotos, Risskartierung vor Bau)', 'AR', 'AR', 'normal'],
    ['Interimsbetrieb am Standort planen: Lärm, Staub, Erschütterung, Zugänge', 'PL,AR,HYG,AS', 'PL', 'normal'],
    ['Baugrund-/Fundamentprüfung bei Erdgeschoss-/Anbaulösung', 'AR', 'AR', 'normal'],
    ['Standortentscheidung dokumentieren und freigeben lassen', 'PL', 'PL', 'hoch'],
  ]],
  4: ['Phase 4 – Planung (Entwurfs- und Ausführungsplanung)', [
    ['Planungsteam beauftragen und Schnittstellenmatrix der Gewerke erstellen', 'PL,AR', 'PL', 'hoch'],
    ['Raumbuch anlegen und mit Soll-Anforderungen je Gewerk füllen', 'PL,AR,MT', 'PL', 'hoch', 'Grundlage für alle Fachplanungen'],
    ['Herstellervorgaben (Site Planning Guide) einarbeiten und versionieren', 'MT', 'MT', 'hoch'],
    ['Entwurfsplanung Architektur: Grundrisse, Schnitte, Türbreiten, Fluchtwege', 'AR', 'AR', 'hoch'],
    ['Werkplanung mit finalen Gerätemaßen und Fundamentplan abgleichen', 'AR,MT', 'AR', 'hoch'],
    ['Bodenaufbau planen: Lastverteilplatte, Schwingungsentkopplung, Leitfähigkeit', 'AR', 'AR', 'hoch'],
    ['Deckenkonstruktion für Deckenstative/Monitorampeln auslegen', 'AR,MT', 'AR', 'normal', null, 'Angiographie,Hybrid-OP,CT'],
    ['HF-Kabine planen: Schirmklasse, Tür, Fenster, Filterplatte, Durchführungen', 'MT,AR,ELT', 'MT', 'hoch', null, 'MRT'],
    ['Quenchrohr-Führung planen (Querschnitt, Ausblasort, Wetterschutz, Vogelschutz)', 'MT,AR,LÜF', 'MT', 'hoch', null, 'MRT'],
    ['Magnetfeldzonen (0,5 mT-Linie) planen und Zutrittskonzept ableiten', 'MT,StrS,AS', 'MT', 'hoch', null, 'MRT'],
    ['Strahlenschutzberechnung beauftragen (Bleigleichwerte Wände/Türen/Fenster/Decken)', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Elektroplanung: Anschlussleistung, Einspeisung, Unterverteilung Gerät, Selektivität', 'ELT', 'ELT', 'hoch'],
    ['AV/SV/ZSV-Konzept je Raum festlegen (DIN VDE 0100-710, Raumgruppen)', 'ELT', 'ELT', 'hoch'],
    ['USV-Bedarf für Rechner/Injektor/Notbeleuchtung dimensionieren', 'ELT', 'ELT', 'normal'],
    ['Potentialausgleich und Erdung planen (zentraler PA-Punkt, ZSV-Bereiche)', 'ELT', 'ELT', 'hoch'],
    ['Beleuchtungsplanung: Untersuchungslicht, Dimmung, Patientenbeleuchtung, Notlicht', 'ELT,AR', 'ELT', 'normal'],
    ['Kabelwege/Trassen planen; Trennung Energie/Daten/geräteeigene Kabel', 'ELT,IT,MT', 'ELT', 'normal'],
    ['Kühllastberechnung Technikraum/Untersuchungsraum erstellen', 'KÄL,LÜF', 'KÄL', 'hoch'],
    ['Kaltwasserversorgung Gerät planen (Vorlauftemperatur, Redundanz, Notkühlung)', 'KÄL', 'KÄL', 'hoch', null, 'MRT,CT,PET-CT,Linearbeschleuniger'],
    ['RLT-Planung: Luftwechsel, Druckstufen, Filterklassen, Temperatur-/Feuchtefenster', 'LÜF,HYG', 'LÜF', 'hoch'],
    ['Sauerstoffüberwachung Technikraum/Untersuchungsraum planen (Heliumverdrängung)', 'MSR,MT,AS', 'MSR', 'hoch', null, 'MRT'],
    ['Heizlast und Wärmeabgabe bewerten; Nachheizung/Kühlung Bedienraum', 'HZG,LÜF', 'HZG', 'niedrig'],
    ['Sanitärplanung: Waschplätze, Ausgussbecken, Bodenabläufe, Rückstausicherung', 'SAN,HYG', 'SAN', 'normal'],
    ['Medizinische Gase planen: O2, Druckluft, Vakuum, Entnahmestellen, AGFS', 'SAN,MT', 'SAN', 'normal'],
    ['MSR/GLT-Planung: Datenpunkte, Störmeldungen, Aufschaltung Leitwarte', 'MSR', 'MSR', 'normal'],
    ['Brandschutzkonzept fortschreiben: Abschottungen, Melder, Wandhydranten, Feuerwehrplan', 'BS,AR', 'BS', 'hoch'],
    ['Türen/Zargen: Strahlenschutz, HF-Dichtung, Fluchtweg, Automatik, Breiten', 'AR,StrS,MT', 'AR', 'normal'],
    ['IT-Planung: Datendosen, WLAN, Netztrennung Medizintechnik, Firewallzonen', 'IT', 'IT', 'hoch'],
    ['Planfreigabe Entwurf durch Nutzer und Betreiber dokumentieren; Planstand einfrieren', 'PL', 'PL', 'hoch', 'Raumbuch-Planstand „Entwurf" erzeugen'],
    ['Ausführungsplanung aller Gewerke koordinieren und Kollisionsprüfung durchführen', 'PL,AR', 'AR', 'hoch'],
  ]],
};
