// Dokumente A–F (genau 67), Raumbuch-Attribute, Raumtypen
const dokumente = {
  A: ['Bedarf, Genehmigungen und Behörden', [
    ['Bedarfsanforderung / Projektauftrag', 'PL', 'Freigegebener Projektauftrag mit Bedarfsbegründung der Klinik'],
    ['Wirtschaftlichkeitsbetrachtung', 'PL', 'Investitions- und Betriebskostenrechnung mit Amortisation'],
    ['Förderbescheid inkl. Auflagen', 'PL', 'Bewilligung der Fördermittel mit Nebenbestimmungen'],
    ['Baugenehmigung / Bauanzeige', 'AR', 'Baurechtliche Freigabe der Umbaumaßnahme'],
    ['Strahlenschutz-Genehmigung/-Anzeige', 'StrS', 'Genehmigung bzw. Anzeige nach StrlSchG für den Betrieb'],
    ['Bestellung Strahlenschutzbeauftragter', 'StrS', 'Benennungsschreiben mit Zuständigkeitsbereich'],
    ['Statik-Gutachten Aufstellort', 'AR', 'Tragfähigkeitsnachweis für Gerätelasten'],
    ['Schwingungsgutachten', 'AR', 'Messbericht Schwingungen mit Bewertung gegen Herstellergrenzwerte'],
    ['Schadstoffgutachten / Freimessung', 'AS', 'Beprobung und Freigabe nach Sanierung'],
    ['Gefährdungsbeurteilungen (Magnetfeld/Baustelle)', 'AS', 'GBU nach ArbSchG inkl. Maßnahmen'],
  ]],
  B: ['Vergabe und Vertrag', [
    ['Leistungsverzeichnis Großgerät', 'VG', 'Ausschreibungsunterlage mit technischen Anforderungen'],
    ['Vergabevermerk / Zuschlagsdokumentation', 'VG', 'Dokumentation der Angebotswertung und Vergabeentscheidung'],
    ['Kaufvertrag / Auftragsbestätigung Gerät', 'VG', 'Vertragsdokument mit Lieferumfang, Preisen und Terminen'],
    ['Wartungs-/Servicevertrag', 'VG', 'Vollwartungs- oder Servicevertrag mit Reaktionszeiten'],
    ['Finale Installationsplanung des Herstellers', 'MT', 'Verbindliche Installationszeichnungen und bauseitige Anforderungen'],
    ['Bauverträge / Nachunternehmerliste', 'AR', 'VOB-Verträge der Baugewerke'],
    ['Terminplan (Vertragsbasis)', 'PL', 'Abgestimmter Rahmenterminplan als Vertragsbestandteil'],
    ['Transport- und Montageversicherungsnachweis', 'VG', 'Versicherungsbestätigung für Lieferung und Montage'],
    ['Bürgschaften (Anzahlung/Gewährleistung)', 'VG', 'Sicherheiten gemäß Vertrag'],
    ['Demontage-/Rücknahmevereinbarung Altgerät', 'MT', 'Regelung zu Abbau, Abtransport und Verwertung'],
  ]],
  C: ['Cybersecurity und IT', [
    ['MDS2-Formular des Herstellers', 'IT', 'Manufacturer Disclosure Statement for Medical Device Security'],
    ['IT-Sicherheitskonzept / Netzsegmentierung', 'IT', 'Zonenmodell, Firewall-Regeln, Härtungsvorgaben'],
    ['Fernwartungsvereinbarung', 'IT', 'Zugriffsweg, Protokollierung und Freigabeprozess'],
    ['Patch- und Update-Vereinbarung', 'IT', 'Verantwortlichkeiten und Zyklen für Sicherheitsupdates'],
    ['Netzplan / IP-Konzept Modalität', 'IT', 'Netzwerkanbindung mit Adressen und VLANs'],
    ['Schnittstellenspezifikation DICOM/HL7', 'IT', 'Conformance Statements und Mapping-Festlegungen'],
    ['Integrationstest-Protokoll RIS/PACS', 'IT', 'Nachweis der erfolgreichen Anbindung inkl. Worklist'],
    ['Freigabe Informationssicherheit (ISB)', 'IT', 'Freigabeerklärung des Informationssicherheitsbeauftragten'],
    ['Datenschutz-Dokumentation (DSFA/VVT-Beitrag)', 'PL', 'Datenschutzrechtliche Bewertung der Verarbeitung'],
    ['IT-Notfallkonzept Modalität', 'IT', 'Downtime-Verfahren und Wiederanlaufplan'],
  ]],
  D: ['Technische Nachweise Bau und TGA', [
    ['Strahlenschutzberechnung', 'StrS', 'Berechnung der Abschirmung mit Bleigleichwerten'],
    ['Bleigleichwert-Nachweis / Einbaudokumentation', 'StrS', 'Materialnachweise und Fotodokumentation der Abschirmung'],
    ['HF-Zwischenmessung Kabine', 'MT', 'Messprotokoll Schirmdämpfung nach Kabinenmontage'],
    ['HF-Endmessung Kabine', 'MT', 'Abschlussmessung der HF-Schirmdämpfung'],
    ['Druckprobenprotokolle Kaltwasser', 'KÄL', 'Dichtheitsnachweis der Kühlkreisläufe'],
    ['Druckproben-/Reinheitsprotokolle medizinische Gase', 'SAN', 'Abnahmeprüfung nach DIN EN ISO 7396-1'],
    ['E-Messprotokolle (Iso, Schleife, RCD)', 'ELT', 'Elektrische Sicherheitsmessungen der Installation'],
    ['Abnahmeprotokoll DIN VDE 0100-710', 'ELT', 'Prüfbericht für medizinisch genutzte Bereiche'],
    ['Netzersatz-/USV-Funktionsprobe', 'ELT', 'Protokoll Lastübernahme und Autonomiezeit'],
    ['RLT-Einregulierungsprotokoll', 'LÜF', 'Volumenströme, Druckverhältnisse, Filterklassen'],
    ['Brandschutz-Abschottungsliste mit Nachweisen', 'BS', 'Verzeichnis aller Abschottungen mit Zulassungen'],
    ['Wirk-Prinzip-Prüfung BMA/Lüftung', 'BS', 'Nachweis des Zusammenwirkens der Brandschutztechnik'],
    ['IT-Verkabelungsmessprotokolle', 'IT', 'Abnahmemessung Kupfer/LWL-Strecken'],
    ['Fundament-/Lastverteilplatten-Abnahme', 'AR', 'Nachweis der Ausführung nach Herstellervorgabe'],
  ]],
  E: ['Abnahme, Prüfung und Einweisung', [
    ['Sachverständigen-Prüfbericht Strahlenschutz', 'StrS', 'Prüfung vor Inbetriebnahme mit Behördenfreigabe'],
    ['Abnahmeprüfung nach QS-Richtlinie', 'MT', 'Abnahmeprüfung mit Bezugswerten für Konstanzprüfung'],
    ['Geräteabnahmeprotokoll Hersteller', 'MT', 'Funktionsnachweis und Spezifikationsabgleich'],
    ['Sicherheitstechnische Kontrolle (STK) Erstprüfung', 'MT', 'Erstprüfung nach MPBetreibV'],
    ['DGUV-V3-Prüfprotokoll', 'ELT', 'Elektrische Prüfung der Anlagen und Betriebsmittel'],
    ['VOB-Abnahmeprotokolle je Gewerk', 'AR', 'Förmliche Bauabnahmen mit Mängellisten'],
    ['Brandschutz-Abnahmebescheinigung', 'BS', 'Freigabe durch Prüfsachverständigen'],
    ['Hygiene-Abnahmeprotokoll', 'HYG', 'Freigabe durch Krankenhaushygiene'],
    ['Magnetfeldkarte / Zonenkennzeichnung', 'MT', 'Dokumentation der 0,5-mT-Linie und Zutrittsregelung'],
    ['Ersteinweisung nach § 10 MPBetreibV', 'MT', 'Nachweis der Ersteinweisung durch Herstellerbeauftragten'],
    ['Einweisungsnachweise Anwender', 'MT', 'Unterschriebene Einweisungsliste aller Anwender'],
    ['Strahlenschutzunterweisungen', 'StrS', 'Nachweis der jährlichen Unterweisungen'],
    ['Notfall-/Quencheinweisung', 'AS', 'Unterweisung Notfallszenarien im MR-Bereich'],
  ]],
  F: ['Betrieb und Übergabe', [
    ['Medizinproduktebuch / Bestandsverzeichnis', 'MT', 'Führung nach MPBetreibV ab Inbetriebnahme'],
    ['Wartungsplan / Wartungsvertrag aktiviert', 'MT', 'Terminierte Wartungen und Zuständigkeiten'],
    ['Revisionsunterlagen / Bestandspläne', 'AR', 'As-built-Pläne aller Gewerke'],
    ['Raumbuch as built', 'PL', 'Eingefrorener Raumbuch-Endstand für den Betrieb'],
    ['Betriebsanweisungen (Magnetfeld/Strahlenschutz/Notfall)', 'AS', 'Ausgehängte Anweisungen für den Betrieb'],
    ['Übergabeprotokoll an Betrieb/CAFM', 'PL', 'Formale Übergabe mit Anlagenliste'],
    ['Gewährleistungsübersicht', 'PL', 'Fristen und Ansprechpartner je Vertrag'],
    ['Verwendungsnachweis Fördermittel', 'PL', 'Abschließender Nachweis gegenüber Fördergeber'],
    ['Entsorgungs-/Verwertungsnachweise Altgerät', 'MT', 'Nachweis inkl. Datenträgerlöschung'],
    ['Projektabschlussbericht', 'PL', 'Abschlussbericht mit Kosten- und Terminbilanz'],
  ]],
};

const attribute = [
  // AR – Architektur/Bau
  ['AR', 'Bodenbelastung', 'zahl', 'kN/m²', null, 'Zulässige Flächenlast am Aufstellort'],
  ['AR', 'Punktlast Gerät', 'zahl', 'kN', null, 'Maximale Punktlast je Aufstellfuß'],
  ['AR', 'Lichte Raumhöhe', 'zahl', 'm', null, 'Nach Ausbau, unter Decke'],
  ['AR', 'Türbreite lichte Öffnung', 'zahl', 'cm', null, 'Wichtig für Einbringung und Betten'],
  ['AR', 'Bodenbelag', 'auswahl', null, 'PVC leitfähig,Kautschuk,Fliese,Estrich', 'Leitfähigkeit im Untersuchungsraum beachten'],
  ['AR', 'Schwingungsentkopplung', 'janein', null, null, 'Erforderlich laut Herstellervorgabe?'],
  ['AR', 'Lastverteilplatte', 'janein', null, null, null],
  ['AR', 'Deckenabhängung für Stative', 'janein', null, null, 'Unterkonstruktion für Deckenstativ/Ampel'],
  // ELT
  ['ELT', 'Anschlussleistung Gerät', 'zahl', 'kVA', null, 'Lt. Herstellerdatenblatt'],
  ['ELT', 'Einspeisung Querschnitt', 'text', null, null, 'z. B. 4×95 mm² Cu'],
  ['ELT', 'Steckdosen AV', 'zahl', 'Stk', null, 'Allgemeine Versorgung'],
  ['ELT', 'Steckdosen SV', 'zahl', 'Stk', null, 'Sicherheitsversorgung (NEA)'],
  ['ELT', 'Steckdosen ZSV', 'zahl', 'Stk', null, 'Zusätzliche Sicherheitsversorgung (IT-System)'],
  ['ELT', 'Raumgruppe VDE 0100-710', 'auswahl', null, '0,1,2', null],
  ['ELT', 'Potentialausgleich', 'janein', null, null, 'Zentraler PA-Punkt vorhanden'],
  ['ELT', 'USV-Versorgung', 'janein', null, null, 'Für Rechner/Konsole'],
  ['ELT', 'Beleuchtungsstärke', 'zahl', 'lx', null, 'Nach ASR/DIN EN 12464'],
  ['ELT', 'Dimmbare Beleuchtung', 'janein', null, null, 'Für Untersuchungsbetrieb'],
  ['ELT', 'Not-Aus Gerät', 'janein', null, null, 'Position mit Nutzer abstimmen'],
  // IT
  ['IT', 'Datendosen', 'zahl', 'Stk', null, 'Doppeldosen RJ45'],
  ['IT', 'LWL-Anbindung', 'janein', null, null, 'Direktanbindung an Verteiler'],
  ['IT', 'Netzwerksegment/VLAN', 'text', null, null, 'z. B. VLAN Medizintechnik 210'],
  ['IT', 'WLAN-Ausleuchtung', 'janein', null, null, null],
  ['IT', 'Patchweg dokumentiert', 'text', null, null, 'Verteiler/Port'],
  // MT
  ['MT', 'Geräteliste Raum', 'text', null, null, 'Hauptgerät und Zusatzgeräte'],
  ['MT', 'Deckenstativ', 'janein', null, null, null],
  ['MT', 'Injektor-Standort', 'text', null, null, null],
  ['MT', 'HF-Schirmdämpfung Soll', 'zahl', 'dB', null, 'Lt. Hersteller, typ. ≥ 90 dB'],
  ['MT', 'Magnetfeld 0,5-mT-Linie', 'text', null, null, 'Verlauf/Kennzeichnung'],
  ['MT', 'Patientenüberwachung', 'text', null, null, 'Monitoring, Kamera, Sprechanlage'],
  ['MT', 'Medizinische Gase am Platz', 'janein', null, null, null],
  // LÜF
  ['LÜF', 'Luftwechselrate', 'zahl', '1/h', null, 'Lt. Hygiene-/Herstellervorgabe'],
  ['LÜF', 'Raumtemperatur Sollbereich', 'text', '°C', null, 'z. B. 20–24 °C, ±1 K/h Gradient'],
  ['LÜF', 'Relative Feuchte Sollbereich', 'text', '%', null, 'z. B. 40–60 %'],
  ['LÜF', 'Druckstufe', 'auswahl', null, 'Überdruck,Neutral,Unterdruck', null],
  ['LÜF', 'Filterklasse Zuluft', 'text', null, null, 'z. B. ePM1 55% + HEPA je Anforderung'],
  ['LÜF', 'Quench-Abluftführung', 'janein', null, null, 'Nur MRT: Verhalten bei Quench geklärt'],
  // KÄL
  ['KÄL', 'Kühllast Gerät', 'zahl', 'kW', null, 'Wärmeabgabe an Kaltwasser'],
  ['KÄL', 'Kühllast Raum (Luft)', 'zahl', 'kW', null, 'Wärmeabgabe an Raumluft'],
  ['KÄL', 'Kaltwasseranschluss', 'janein', null, null, null],
  ['KÄL', 'Vorlauftemperatur', 'zahl', '°C', null, 'Lt. Hersteller, typ. 6–12 °C'],
  ['KÄL', 'Redundanz/Notkühlung', 'janein', null, null, 'Bei Ausfall Hauptkälte'],
  // SAN
  ['SAN', 'Waschplatz', 'janein', null, null, null],
  ['SAN', 'Ausgussbecken', 'janein', null, null, null],
  ['SAN', 'Bodenablauf', 'janein', null, null, 'Rückstauebene beachten'],
  ['SAN', 'Medizinische Gase', 'auswahl', null, 'O2,Druckluft,Vakuum,O2+Druckluft,O2+Druckluft+Vakuum,keine', null],
  ['SAN', 'Gase-Entnahmestellen', 'zahl', 'Stk', null, null],
  // StrS
  ['StrS', 'Bleigleichwert Wände', 'zahl', 'mm Pb', null, 'Aus Strahlenschutzberechnung'],
  ['StrS', 'Bleigleichwert Tür', 'zahl', 'mm Pb', null, null],
  ['StrS', 'Bleigleichwert Fenster', 'zahl', 'mm Pb', null, 'Bleiglas Sichtfenster'],
  ['StrS', 'Bleigleichwert Decke/Boden', 'zahl', 'mm Pb', null, null],
  ['StrS', 'Kontrollbereich', 'janein', null, null, 'Kennzeichnung erforderlich'],
  ['StrS', 'Warnleuchte/Türkontakt', 'janein', null, null, null],
  // MSR
  ['MSR', 'GLT-Aufschaltung', 'janein', null, null, null],
  ['MSR', 'Datenpunkte Anzahl', 'zahl', 'Stk', null, null],
  ['MSR', 'Störmeldung an Leitwarte', 'janein', null, null, 'Kritische Meldungen definiert'],
  ['MSR', 'O2-Überwachung', 'janein', null, null, 'Nur MRT-Technik/Untersuchungsraum'],
  ['MSR', 'Temperaturüberwachung Technikraum', 'janein', null, null, null],
  // HZG
  ['HZG', 'Heizlast', 'zahl', 'kW', null, null],
  ['HZG', 'Heizsystem', 'auswahl', null, 'Statisch,Lüftung,Keins', null],
  // BS
  ['BS', 'Brandabschnitt', 'text', null, null, 'Zuordnung/Bezeichnung'],
  ['BS', 'Brandmelder Anzahl', 'zahl', 'Stk', null, null],
  ['BS', 'Feuerwiderstand Türen', 'text', null, null, 'z. B. T30-RS'],
  ['BS', 'Löschmittel MR-tauglich', 'janein', null, null, 'Amagnetischer Feuerlöscher im MR-Bereich'],
  // HYG
  ['HYG', 'Raumklasse Hygiene', 'auswahl', null, 'I,Ia,Ib,II,ohne', 'Einstufung durch Krankenhaushygiene'],
  ['HYG', 'Händedesinfektionsspender', 'zahl', 'Stk', null, null],
  ['HYG', 'Oberflächen desinfektionsbeständig', 'janein', null, null, null],
  // AS
  ['AS', 'Fluchtweg', 'text', null, null, 'Führung/Länge'],
  ['AS', 'Notruf/Patientenruf', 'janein', null, null, null],
  ['AS', 'Augenspüleinrichtung', 'janein', null, null, 'Bei KM-/Chemikalienhandling'],
];

const raumtypen = [
  ['MRT-Untersuchungsraum', ['AR:Bodenbelastung', 'AR:Lichte Raumhöhe', 'AR:Türbreite lichte Öffnung', 'AR:Bodenbelag', 'AR:Schwingungsentkopplung', 'AR:Lastverteilplatte', 'ELT:Anschlussleistung Gerät', 'ELT:Steckdosen ZSV', 'ELT:Raumgruppe VDE 0100-710', 'ELT:Potentialausgleich', 'ELT:Dimmbare Beleuchtung', 'ELT:Not-Aus Gerät', 'MT:HF-Schirmdämpfung Soll', 'MT:Magnetfeld 0,5-mT-Linie', 'MT:Patientenüberwachung', 'MT:Medizinische Gase am Platz', 'LÜF:Luftwechselrate', 'LÜF:Raumtemperatur Sollbereich', 'LÜF:Relative Feuchte Sollbereich', 'LÜF:Quench-Abluftführung', 'KÄL:Kühllast Raum (Luft)', 'SAN:Medizinische Gase', 'MSR:O2-Überwachung', 'BS:Löschmittel MR-tauglich', 'HYG:Raumklasse Hygiene', 'AS:Fluchtweg', 'AS:Notruf/Patientenruf', 'IT:Datendosen']],
  ['CT-Untersuchungsraum', ['AR:Bodenbelastung', 'AR:Türbreite lichte Öffnung', 'ELT:Anschlussleistung Gerät', 'ELT:Steckdosen ZSV', 'ELT:Raumgruppe VDE 0100-710', 'ELT:Not-Aus Gerät', 'StrS:Bleigleichwert Wände', 'StrS:Bleigleichwert Tür', 'StrS:Bleigleichwert Fenster', 'StrS:Kontrollbereich', 'StrS:Warnleuchte/Türkontakt', 'MT:Patientenüberwachung', 'LÜF:Luftwechselrate', 'LÜF:Raumtemperatur Sollbereich', 'KÄL:Kühllast Raum (Luft)', 'SAN:Medizinische Gase', 'HYG:Raumklasse Hygiene', 'AS:Notruf/Patientenruf', 'IT:Datendosen']],
  ['Angiographie-/Hybrid-OP-Raum', ['AR:Deckenabhängung für Stative', 'AR:Lichte Raumhöhe', 'ELT:Anschlussleistung Gerät', 'ELT:Steckdosen ZSV', 'ELT:Raumgruppe VDE 0100-710', 'ELT:USV-Versorgung', 'StrS:Bleigleichwert Wände', 'StrS:Bleigleichwert Tür', 'StrS:Kontrollbereich', 'MT:Deckenstativ', 'MT:Injektor-Standort', 'MT:Medizinische Gase am Platz', 'LÜF:Luftwechselrate', 'LÜF:Druckstufe', 'LÜF:Filterklasse Zuluft', 'SAN:Medizinische Gase', 'SAN:Gase-Entnahmestellen', 'HYG:Raumklasse Hygiene', 'IT:Datendosen']],
  ['Technikraum', ['ELT:Anschlussleistung Gerät', 'ELT:Steckdosen AV', 'KÄL:Kühllast Gerät', 'KÄL:Kaltwasseranschluss', 'KÄL:Vorlauftemperatur', 'KÄL:Redundanz/Notkühlung', 'LÜF:Raumtemperatur Sollbereich', 'MSR:GLT-Aufschaltung', 'MSR:Temperaturüberwachung Technikraum', 'MSR:O2-Überwachung', 'MSR:Störmeldung an Leitwarte', 'BS:Brandmelder Anzahl', 'IT:Datendosen']],
  ['Bedienraum/Schaltraum', ['ELT:Steckdosen SV', 'ELT:USV-Versorgung', 'ELT:Beleuchtungsstärke', 'StrS:Bleigleichwert Fenster', 'IT:Datendosen', 'IT:Netzwerksegment/VLAN', 'LÜF:Raumtemperatur Sollbereich', 'AS:Notruf/Patientenruf', 'HYG:Händedesinfektionsspender']],
  ['Vorbereitung/Patientenhaltung', ['SAN:Waschplatz', 'SAN:Medizinische Gase', 'SAN:Gase-Entnahmestellen', 'ELT:Steckdosen SV', 'ELT:Raumgruppe VDE 0100-710', 'MT:Patientenüberwachung', 'HYG:Raumklasse Hygiene', 'HYG:Händedesinfektionsspender', 'AS:Notruf/Patientenruf', 'IT:Datendosen']],
  ['Umkleide Patienten', ['AR:Türbreite lichte Öffnung', 'ELT:Steckdosen AV', 'AS:Notruf/Patientenruf', 'HYG:Händedesinfektionsspender']],
  ['Wartebereich', ['ELT:Steckdosen AV', 'ELT:Beleuchtungsstärke', 'LÜF:Luftwechselrate', 'BS:Brandmelder Anzahl', 'IT:WLAN-Ausleuchtung']],
  ['Befundraum', ['IT:Datendosen', 'IT:Netzwerksegment/VLAN', 'ELT:Steckdosen SV', 'ELT:Beleuchtungsstärke', 'LÜF:Raumtemperatur Sollbereich']],
];

module.exports = { dokumente, attribute, raumtypen };
