// Phasen 10–14
module.exports = {
  10: ['Phase 10 – Anlieferung und Montage Großgerät', [
    ['Liefertermin bestätigen; Anlieferlogistik final abstimmen (Uhrzeit, Route, Sperrungen)', 'MT,PL,AR', 'MT', 'hoch'],
    ['Kranstellung/Schwertransport genehmigen lassen (Straßensperrung, Polizei)', 'AR,PL', 'AR', 'normal'],
    ['Einbringweg vorbereiten: Schutzmaßnahmen, Bodenplatten, Demontagen', 'AR,MT', 'AR', 'hoch'],
    ['Bauseitige Voraussetzungen nach Hersteller-Checkliste bestätigen (Ready-for-Delivery)', 'MT,AR,ELT,KÄL', 'MT', 'hoch'],
    ['Baureinigung/Feinstaubfreiheit vor Einbringung sicherstellen', 'AR,HYG', 'AR', 'normal'],
    ['Anlieferung überwachen; Transportschäden sofort dokumentieren', 'MT', 'MT', 'hoch'],
    ['Magnet einbringen und positionieren; Achsen/Feldlage prüfen', 'MT,AR', 'MT', 'hoch', null, 'MRT'],
    ['Gantry/System einbringen und auf Fundament montieren', 'MT', 'MT', 'hoch'],
    ['Heliumbefüllung/Kryostat-Arbeiten begleiten; Sicherheitsbereich absichern', 'MT,AS', 'MT', 'hoch', null, 'MRT'],
    ['Geräteeigene Verkabelung durch Hersteller; Schnittstellen zu Bauseite klären', 'MT,ELT', 'MT', 'normal'],
    ['Kaltwasseranschluss Gerät herstellen; Durchfluss/Temperatur einregulieren', 'KÄL,MT', 'KÄL', 'hoch'],
    ['Deckenstative/Monitorampeln montieren und Traglast prüfen', 'MT,AR', 'MT', 'normal', null, 'Angiographie,Hybrid-OP,CT'],
    ['Patiententisch, Injektor, Zubehör montieren und anschließen', 'MT', 'MT', 'normal'],
    ['HF-Enddichtung nach Kabeldurchführungen prüfen', 'MT', 'MT', 'hoch', null, 'MRT'],
    ['Montagefortschritt und Restpunkte des Herstellers protokollieren', 'MT,PL', 'MT', 'normal'],
    ['Erstinbetriebnahme durch Hersteller (Power-on) begleiten', 'MT,ELT', 'MT', 'hoch'],
    ['Magnetfeld-Kennzeichnung und Zutrittskontrolle aktivieren', 'MT,AS,StrS', 'MT', 'hoch', null, 'MRT'],
    ['Einweisung Baustellenpersonal in Gefahrenbereiche (Magnet, Strahlung)', 'AS,MT', 'AS', 'normal'],
  ]],
  11: ['Phase 11 – Technische Inbetriebnahme und Messungen', [
    ['Elektrische Sicherheitsprüfungen: Schleifenimpedanz, Iso-Messung, RCD-Tests', 'ELT', 'ELT', 'hoch'],
    ['Abnahmemessung DIN VDE 0100-710: PA, ZSV-Umschaltzeiten, IT-System-Überwachung', 'ELT', 'ELT', 'hoch'],
    ['Netzersatzprobe: Lastübernahme AV/SV/ZSV mit Gerät im Betrieb testen', 'ELT,MT', 'ELT', 'hoch'],
    ['USV-Autonomietest unter Last durchführen', 'ELT', 'ELT', 'normal'],
    ['HF-Endmessung Kabine mit Protokoll (Schirmdämpfung über Frequenzband)', 'MT', 'MT', 'hoch', null, 'MRT'],
    ['Magnetfeldkarte messen und 0,5-mT-Zone kennzeichnen', 'MT,StrS', 'MT', 'hoch', null, 'MRT'],
    ['Strahlenschutz-Abnahmemessung durch Sachverständigen (Ortsdosisleistung)', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Sauerstoffmangel-Warnanlage kalibrieren und Alarmkette testen', 'MSR,AS', 'MSR', 'hoch', null, 'MRT'],
    ['RLT einregulieren: Volumenströme, Druckstufen, Temperatur-/Feuchtefahrt', 'LÜF', 'LÜF', 'hoch'],
    ['Hygiene-Abnahme RLT (ggf. Luftkeimmessung) durchführen', 'HYG,LÜF', 'HYG', 'normal'],
    ['Kälteanlage einregulieren; Redundanz-/Störszenarien testen (Notkühlung)', 'KÄL', 'KÄL', 'hoch'],
    ['Medizinische Gase: Abnahmeprüfung, Reinheitsmessung, Kennzeichnung', 'SAN', 'SAN', 'hoch'],
    ['GLT-Aufschaltung testen: Datenpunkte, Störmeldungen, Trending', 'MSR', 'MSR', 'normal'],
    ['BMA/Sprinkler-Anpassungen prüfen und Wirk-Prinzip-Prüfung durchführen', 'BS,MSR', 'BS', 'hoch'],
    ['Quench-Notfallszenario prüfen (Auslöseorgane, Türöffnung, Lüftungsverhalten)', 'MT,AS,LÜF', 'MT', 'hoch', null, 'MRT'],
    ['Bildqualitäts- und Kalibriermessungen des Herstellers begleiten (Phantome)', 'MT', 'MT', 'hoch'],
    ['Abnahmeprüfung nach QS-Richtlinie/DIN 6868 ff. mit Medizinphysik durchführen', 'MT,StrS', 'MT', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['IT-Integrationstest im Wirkbetrieb: Worklist, Bildversand, Befundworkflow, Dosisdaten', 'IT,MT', 'IT', 'hoch'],
    ['Fernwartungszugang produktiv testen und protokollieren', 'IT,MT', 'IT', 'normal'],
    ['DGUV-V3-Prüfung ortsveränderlicher/ortsfester Anlagen dokumentieren', 'ELT,AS', 'ELT', 'normal'],
    ['Messprotokolle aller Gewerke einsammeln und im Dokumentenregister ablegen', 'PL', 'PL', 'hoch'],
    ['Restpunkte aus Inbetriebnahme in Mängelliste überführen', 'PL,AR', 'PL', 'normal'],
  ]],
  12: ['Phase 12 – Abnahmen, Prüfungen und Einweisungen', [
    ['Bau-Abnahmen je Gewerk (VOB) mit Mängellisten durchführen', 'AR,PL', 'AR', 'hoch'],
    ['TGA-Abnahmen: ELT, RLT, Kälte, Sanitär, MSR mit Protokollen', 'ELT,LÜF,KÄL,SAN,MSR', 'AR', 'hoch'],
    ['Brandschutz-Abnahme: Abschottungen, Türen, BMA, Feuerwehrpläne aktualisiert', 'BS', 'BS', 'hoch'],
    ['Sachverständigen-Abnahme Strahlenschutz und Behördenfreigabe einholen', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Hygiene-Endabnahme und Schlussreinigung freigeben', 'HYG', 'HYG', 'normal'],
    ['Arbeitsschutz-Begehung: Kennzeichnung, Fluchtwege, Notfallausstattung', 'AS', 'AS', 'normal'],
    ['Geräteabnahme mit Hersteller: Funktionsnachweis, Spezifikationsabgleich, Restpunkte', 'MT,PL', 'MT', 'hoch'],
    ['Abnahmeprüfung Medizinprodukt inkl. sicherheitstechnischer Kontrolle dokumentieren', 'MT', 'MT', 'hoch'],
    ['Konstanzprüfungs-Baseline aufnehmen und QS-Zyklen festlegen', 'MT,StrS', 'MT', 'normal', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Medizinproduktebuch/Bestandsverzeichnis anlegen (MPBetreibV)', 'MT', 'MT', 'hoch'],
    ['Ersteinweisung durch Hersteller für Gerätebeauftragte durchführen (§ 10 MPBetreibV)', 'MT', 'MT', 'hoch'],
    ['Einweisungsnachweise aller Anwender einsammeln und ablegen', 'MT', 'MT', 'hoch'],
    ['Einweisung Technik/Betrieb: Medienversorgung, Störmeldungen, Notabschaltungen', 'MT,ELT,KÄL,LÜF,MSR', 'MT', 'normal'],
    ['Notfallunterweisungen: Quench, Brand im MR-Bereich, Kontrastmittelzwischenfall', 'AS,MT', 'AS', 'hoch', null, 'MRT'],
    ['Strahlenschutzunterweisungen durchführen und dokumentieren', 'StrS', 'StrS', 'hoch', null, 'CT,Angiographie,Hybrid-OP,PET-CT,Linearbeschleuniger'],
    ['Abnahmereife-Prüfung im System: offene Punkte, fehlende Dokumente, offene Mängel', 'PL', 'PL', 'hoch', 'Bericht „Abnahmereife" nutzen'],
    ['Mängelbeseitigung nachverfolgen; Nachabnahmen terminieren', 'AR,PL', 'AR', 'hoch'],
    ['Bestandsdokumentation einfordern: Revisionspläne, Schemata, Berechnungen', 'AR,ELT,LÜF,KÄL,SAN', 'AR', 'hoch'],
    ['Raumbuch als „As built" einfrieren', 'PL', 'PL', 'hoch'],
    ['Gewährleistungsfristen erfassen (Beginn, Dauer je Vertrag) und Wiedervorlagen setzen', 'PL,VG', 'PL', 'normal'],
    ['Versicherungsmeldung Inbetriebnahme/Neuwert an Betreiberversicherung', 'PL', 'PL', 'niedrig'],
    ['Behördliche Betriebsfreigaben vollständig ablegen', 'PL,StrS', 'PL', 'hoch'],
    ['Probebetrieb mit Testpatienten/Phantomen im Realworkflow durchführen', 'MT,IT,PL', 'MT', 'normal'],
    ['Übergabeprotokoll Bau→Betrieb unterzeichnen', 'PL,AR', 'PL', 'hoch'],
    ['Restleistungsliste mit Terminen vereinbaren', 'AR,PL', 'AR', 'normal'],
    ['Schlüssel-/Transponderübergabe und Zutrittsberechtigungen einrichten', 'AR,PL', 'AR', 'niedrig'],
  ]],
  13: ['Phase 13 – Go-Live und Betriebsübergabe', [
    ['Go-Live-Termin mit Klinik, IT und Hersteller festlegen; Erstbelegungsplan erstellen', 'PL,MT', 'PL', 'hoch'],
    ['Erster Patiententag mit Applikationsbegleitung des Herstellers', 'MT', 'MT', 'hoch'],
    ['Hypercare-Phase vereinbaren (erhöhte Supportbereitschaft erste Wochen)', 'MT,IT', 'MT', 'normal'],
    ['Terminplanung/RIS-Slots aktivieren; Untersuchungsprotokolle freigeben', 'IT,MT', 'MT', 'normal'],
    ['Störmelde- und Eskalationswege für Betrieb kommunizieren (Hotline, Ticket)', 'MT,IT,MSR', 'MT', 'normal'],
    ['Wartungsvertrag aktivieren; erste Wartung terminieren', 'MT,VG', 'MT', 'normal'],
    ['Verbrauchsmaterial/Zubehör-Erstausstattung prüfen (Spulen, Phantome, KM)', 'MT', 'MT', 'niedrig'],
    ['Betriebsanweisungen aushängen (Magnetfeld, Strahlenschutz, Notfall)', 'AS,StrS,MT', 'AS', 'normal'],
    ['Reinigungs-/Aufbereitungsplan mit Hygiene in Betrieb nehmen', 'HYG', 'HYG', 'normal'],
    ['Energie-/Medienverbräuche Startwerte ablesen (Benchmark)', 'ELT,KÄL,MSR', 'MSR', 'niedrig'],
    ['CAFM-Übergabe: Räume, Anlagen, Wartungspläne, As-built-Raumbuch exportieren', 'PL,MSR,AR', 'PL', 'normal'],
    ['Feedbackrunde Nutzer nach 2–4 Wochen durchführen; Nachjustierungen ableiten', 'PL,MT', 'PL', 'normal'],
    ['Leistungsdaten erste Wochen auswerten (Untersuchungszahlen, Ausfälle)', 'PL,MT', 'PL', 'niedrig'],
    ['Offene Restpunkte aus Hypercare in Regelprozesse überführen', 'PL', 'PL', 'normal'],
  ]],
  14: ['Phase 14 – Projektabschluss, Dokumentation und Lessons Learned', [
    ['Dokumentenregister auf Vollständigkeit prüfen (alle „benötigt" erhalten)', 'PL', 'PL', 'hoch', 'Vollständigkeitsbericht nutzen'],
    ['Projektakte final exportieren und revisionssicher ablegen (10 Jahre)', 'PL', 'PL', 'hoch'],
    ['Schlussrechnungen prüfen; Kostenfeststellung nach DIN 276 erstellen', 'PL,VG,AR', 'PL', 'hoch'],
    ['Fördermittel-Verwendungsnachweis fristgerecht einreichen', 'PL,VG', 'PL', 'hoch'],
    ['Bürgschaften/Einbehalte nach Mängelfreiheit freigeben', 'VG,AR', 'VG', 'normal'],
    ['Gewährleistungsbegehung Jahr 1 terminieren (Wiedervorlage)', 'AR,PL', 'AR', 'normal'],
    ['Altgeräte-Verwertung abschließen: Löschnachweis Datenträger, Entsorgungsbelege', 'MT,IT', 'MT', 'normal'],
    ['Projektabschlussbericht für Lenkungskreis erstellen (Kosten, Termine, Qualität)', 'PL', 'PL', 'normal'],
    ['Lessons Learned-Workshop durchführen; Vorschläge für Vorlagenversion erfassen', 'PL', 'PL', 'normal', 'Erkenntnisse als Vorlagen-Vorschläge einreichen'],
    ['Checklisten-/Vorlagenpflege: neue Punkte in nächste Vorlagenversion übernehmen', 'PL', 'PL', 'normal'],
    ['Projektorganisation auflösen; Verantwortungsübergang an Linienbetrieb bestätigen', 'PL', 'PL', 'normal'],
    ['Nachkalkulation Wirtschaftlichkeit nach 12 Monaten einplanen', 'PL', 'PL', 'niedrig'],
    ['Projekt im System archivieren', 'PL', 'PL', 'normal'],
  ]],
};
